export enum ATTACHMENT_TITLES {
	ProfilePicture = "Profile Picture",
	DrivingLicense1 = "Driving License 1",
	DrivingLicense2 = "Driving License 2",
	InsuranceCard1 = "Insurance Card 1",
	InsuranceCard2 = "Insurance Card 2",
	ProviderUploads = "Provider Uploads",
	Signature = "Signature",
	LabOrders = "Lab Orders",
	PracticeLogo = "Logo",
}

const PATIENT_LOG_PERMISSIONS = [
	'GetPatient',
	'GetLabTest',
	'PatientInfo',
	'RemovePatient',
	'CreatePatient',
	'UpdatePatient',
	'FindAllLabTest',
	"AddPatientVital",
	"GetPatientVital",
	'RemoveAppointment',
	"GetPatientProblem",
	'UpdateAppointment',
	'CancelAppointment',
	"AddPatientProblem",
	'GetPatientAllergy',
	"RemovePatientVital",
	'GetPatientProvider',
	'UpdatePatientVital',
	'GetPatientProviders',
	'SendInviteToPatient',
	'RemovePatientProblem',
	'UpdatePatientProblem',
	'FindAllPatientVitals',
	'UpdatePatientProfile',
	'UpdatePatientProvider',
	"RemovePatientAllergy",
	'GetPatientAppointment',
	"FindAllPatientProblem",
	'FetchPatientInsurances',
	'FindPatientAttachments',
	'FindAllPatientProblems',
	'UpdatePatientNoteInfoInputs',
	'UpdatePatientProviderRelation',
	"GetPatientPastUpcomingAppointment",
]

export const PATIENT_LOGGING_PERMISSIONS = PATIENT_LOG_PERMISSIONS?.map((val) => val?.toUpperCase())