import * as Joi from 'joi';
import { OnsetDateType, OtherDateType } from 'src/billings/entities/billing.entity';
import { OrderOfBenefitType } from 'src/insurance/entities/policy.entity';

const chargeItem = Joi.object().keys({
  m1: Joi.string().required(),
  m2: Joi.string().required(),
  m3: Joi.string().required(),
  m4: Joi.string().required(),
  unit: Joi.string().required(),
  units: Joi.string().required(),
  charge: Joi.number().required(),
  diag_ref: Joi.string().required(),
  proc_code: Joi.string().required(),
  diagPointer: Joi.string().required(),
})

export const claimValidation = Joi.object({
  claim_form: Joi.string().required(),
  payerid: Joi.string().required(),
  payer_name: Joi.string().required(),
  pcn: Joi.string().required(),
  pat_name_l: Joi.string().required(),
  pat_name_f: Joi.string().required(),
  pat_addr_1: Joi.string().required(),
  pat_city: Joi.string().required(),
  pat_state: Joi.string().required(),
  pat_zip: Joi.string().required(),
  pat_dob: Joi.string().required(),
  pat_sex: Joi.string().required(),
  pat_rel: Joi.string().required(),
  ins_number: Joi.string().required(),
  accept_assign: Joi.string().required(),
  total_charge: Joi.string().required(),
  bill_name: Joi.string().required(),
  bill_addr_1: Joi.string().required(),
  bill_addr_2: Joi.string().required(),
  bill_city: Joi.string().required(),
  bill_state: Joi.string().required(),
  bill_zip: Joi.string().required(),
  bill_npi: Joi.string().required(),
  bill_phone: Joi.string().required(),
  bill_taxid: Joi.string().required(),
  bill_taxid_type: Joi.string().required(),
  bill_taxonomy: Joi.string().required(),
  from_date_1: Joi.string().required(),
  thru_date: Joi.string().required(),
  charge: Joi.array().items(chargeItem),
  payer_order: Joi.string().valid(OrderOfBenefitType.PRIMARY, OrderOfBenefitType.SECONDARY, OrderOfBenefitType.TERTIARY),
  pat_name_m: Joi.string(),
  pat_addr_2: Joi.string(),
  pat_country: Joi.string().required(),
  pat_phone: Joi.string().required(),
  pat_marital: Joi.string().required(),
  ins_name_l: Joi.string().required(),
  ins_name_f: Joi.string().required(),
  ins_name_m: Joi.string(),
  ins_addr_1: Joi.string().required(),
  ins_addr_2: Joi.string(),
  ins_city: Joi.string().required(),
  ins_state: Joi.string().required(),
  ins_zip: Joi.string().required(),
  ins_group: Joi.string().required(),
  ins_dob: Joi.string().required(),
  ins_sex: Joi.string().required().valid("M", "F", "U"),
  employment_related: Joi.string().required().valid('Y', 'N'),
  auto_accident: Joi.string().required().valid('Y', 'N'),
  other_accident: Joi.string().required().valid('Y', 'N'),
  ref_name_l: Joi.string().required(),
  ref_name_f: Joi.string().required(),
  ref_name_m: Joi.string(),
  ref_id: Joi.string().required(),
  ref_npi: Joi.string().required(),
  cond: Joi.string().required().valid(OnsetDateType.DATE_OF_ACCIDENT, OnsetDateType.DATE_OF_HOSPITALIZATION),
  onset: Joi.string().required().valid(OtherDateType.INITIAL_TREATMENT_DATE, OtherDateType.INITIAL_VISIT_DATE, OtherDateType.LAST_RELATED_VISIT),
  cond_date: Joi.string().required(),
  onset_date: Joi.string().required(),
  hosp_from_date: Joi.string().required(),
  hosp_thru_date: Joi.string().required(),
  clia_number: Joi.string().required(),
  facility_name: Joi.string().required(),
  facility_addr_1: Joi.string().required(),
  facility_addr_2: Joi.string(),
  facility_city: Joi.string().required(),
  facility_state: Joi.string().required(),
  facility_zip: Joi.string().required(),
  facility_npi: Joi.string().required(),
  facility_id: Joi.string().required(),
  prov_name_l: Joi.string().required(),
  prov_name_f: Joi.string().required(),
  prov_name_m: Joi.string(),
  prov_npi: Joi.string().required(),
  ord_name_l: Joi.string().required(),
  ord_name_f: Joi.string().required(),
  ord_name_m: Joi.string(),
  ord_npi: Joi.string().required(),
  place_of_service_1: Joi.string().required(),
  chg_facility_name: Joi.string().required(),
  chg_facility_addr_1: Joi.string().required(),
  chg_facility_addr_2: Joi.string(),
  chg_facility_city: Joi.string().required(),
  chg_facility_state: Joi.string().required(),
  chg_facility_zip: Joi.string().required(),
  chg_facility_npi: Joi.string().required(),
  facility_clia: Joi.string().required(),
  ord_prov_name_l: Joi.string().required(),
  ord_prov_name_f: Joi.string().required(),
  ord_prov_name_m: Joi.string(),
  ord_prov_npi: Joi.string().required(),
  diag_1: Joi.string().optional(),
  diag_2: Joi.string().optional(),
  diag_3: Joi.string().optional(),
  diag_4: Joi.string().optional(),
  diag_5: Joi.string().optional(),
  diag_6: Joi.string().optional(),
  diag_7: Joi.string().optional(),
  diag_8: Joi.string().optional(),
  diag_9: Joi.string().optional(),
  diag_10: Joi.string().optional(),
  diag_11: Joi.string().optional(),
  diag_12: Joi.string().optional(),
})

export const claimMedValidation = Joi.object({
  bill_npi: Joi.string().max(10).required(),
  payerid: Joi.string().required().messages({ 'any.required': "Insurance is missing" }),
  payer_name: Joi.string().required().messages({ 'any.required': "Insurance is missing" }),
  pat_name_l: Joi.string().required().messages({ "any.required": "Patient last name is missing" }),
  pat_name_f: Joi.string().required().messages({ "any.required": "Patient first name is missing" }),
  pat_dob: Joi.string().required().messages({ "any.required": "Patient dob is missing" }),
  pat_sex: Joi.string().required().messages({ "any.required": "Patient gender is missing" }),
  ins_name_l: Joi.string().required().messages({ "any.required": "Insurance last name is missing" }),
  ins_name_f: Joi.string().required().messages({ "any.required": "Insurance first name is missing" }),
  pat_addr_1: Joi.string().required().messages({ "any.required": "Patient address is missing" }),
  pat_city: Joi.string().required().messages({ "any.required": "Patient city is missing" }),
  pat_state: Joi.string().required().messages({ "any.required": "Patient state is missing" }),
  pat_zip: Joi.string().required().messages({ "any.required": "Patient zipCode is missing" }),
  ins_addr_1: Joi.string().required().messages({ "any.required": "Insurance address is missing" }),
  ins_city: Joi.string().required().messages({ "any.required": "Insurance city is missing" }),
  ins_state: Joi.string().required().messages({ "any.required": "Insurance state is missing" }),
  ins_zip: Joi.string().required().messages({ "any.required": "Insurance zipCode is missing" }),
  diag_1: Joi.string().required().messages({ "any.required": "Atleast one diagnose is required" }),
  place_of_service_1: Joi.string().required().messages({ "any.required": "POS code is missing" }),
  from_date_1: Joi.string().required().messages({ "any.required": "Date of service is missing" }),
  facility_name: Joi.string().required().messages({ "any.required": "Facility name is missing" }),
  facility_addr_1: Joi.string().required().messages({ "any.required": "Facility address is missing" }),
  facility_city: Joi.string().required().messages({ "any.required": "Facility city is missing" }),
  facility_state: Joi.string().required().messages({ "any.required": "Facility state is missing" }),
  facility_zip: Joi.string().required().messages({ "any.required": "Facility zipCode is missing" }),
  facility_npi: Joi.string().required().messages({ "any.required": "Facility NPI is missing" }),
  bill_taxid: Joi.string().required().messages({ "any.required": "Facility taxId is missing" }),
}).options({
  abortEarly: false,
});