export const specimenTypesData = [
    { name: "Abscess" },
    { name: "Abscess, Pelvic" },
    { name : "Abscess, Perianal" },
    { name : "Abscess, Rectal" },
    { name : "Abscess, Scrotal" },
    { name : "Abscess, Submandibular" },
    { name : "Abscess, Submaxillary" },
    { name : "Abscess, Testicular" },
    { name : "Air Sample" },
    { name : "Allograft" },
    { name : "Amniotic Fluid" },
    { name : "Amputation" },
    { name : "Antrum, Gastric" },
    { name : "Nasopharynx SWAB" },
    { name : "Aptima SWAB" },
    { name : "Aspirate" },
    { name : "Aspirate, Endotrach" },
    { name : "Aspirate, Gastric" },
    { name : "Aspirate, Nasogastric" },
    { name : "Aspirate, Tracheal" },
    { name : "Aspirate, Transtracheal" },
    { name : "Autopsy" },
    { name : "Basophils" },
    { name : "Bile Fluid" },
    { name : "Biopsy" },
    { name : "Biopsy, Gastric" },
    { name : "Biopsy, Skin" },
    { name : "Biospy, Cone" },
    { name : "Bite" },
    { name : "Bite, Cat" },
    { name : "Bite, Dog" },
    { name : "Bite, Human" },
    { name : "Bite, Insect" },
    { name : "Bite, Reptile" },
    { name : "Bleb" },
    { name : "Blister" },
    { name : "Blood" },
    { name : "Blood bag" },
    { name : "Blood product unit" },
    { name : "Blood, Arterial" },
    { name : "Blood, Autopsy" },
    { name : "Blood, Capillary" },
    { name : "Blood, Cell Saver" },
    { name : " Blood, Fetal" },
    { name : "Blood, Menstrual" },
    { name : "Blood, Venous" },
    { name : "Blood, Whole" },
    { name : "Boil" },
    { name : "Bone" },
    { name : "Bowel contents" }
    ]