import { PracticeType, ServiceCode } from '../../facilities/entities/facility.entity';
import { UserStatus } from '../entities/user.entity';

export const FacilityData = [
    {
        name: "Private Facility", practiceType: PracticeType.HOSPITAL, code: "+02923", mammographyCertificationNumber: "232232",
        cliaIdNumber: "023292", federalTaxId: "232232322", isPrivate: true, revenueCode: "323343433", npi: "232332",
        tamxonomyCode: "2322332", serviceCode: ServiceCode.Emergency_Room_Hospital_23
    }
];

export const RolesData = [
    { role: 'super-admin', customRole: false, description: "super admin has all permissions" },
    { role: 'practice-admin', customRole: false, description: "admin has all permissions of any practice" },
    { role: 'facility-admin', customRole: false, description: "admin has all permissions of any facility" },
    { role: 'emergency-access', customRole: false, description: "emergency access role has facility-admin level permissions" },
    { role: 'doctor', customRole: false, description: "doctor has all permissions related to patients and their medical history" },
    { role: 'nurse', customRole: false, description: "nurse has permissions" },
    { role: 'patient', customRole: false, description: "patient has all permissions for patient portal" },
    { role: 'staff', customRole: false, description: "staff has permissions for staff members and lab records" },
    { role: 'nurse-practitioner', customRole: false, description: "nurse practitioner has all permissions of facility's patients" },
    { role: 'office-manager', customRole: false, description: "office manager has administrative permissions" },
    { role: 'doctor-assistant', customRole: false, description: "doctor assistant has partial permissions of doctor" },
    { role: 'front-desk', customRole: false, description: "front desk assistant has partial permissions of admin" },
    { role: 'biller', customRole: false, description: "biller has permissions of appointment and billing" },
];

export const UsersData = [
    {
        firstName: "Super", lastName: "Admin", password: "super123", email: "admin@alxtel.com", status: UserStatus.ACTIVE,
        phone: "+923426851938", userType: 'super-admin', roleType: 'super-admin', zipCode: "54000", emailVerified: true
    },
];

export const PermissionData = [
    { name: 'emergencyAccess', moduleType: 'Emergency Access' },
    { name: 'fetchAllUsers', moduleType: 'User' },
    { name: 'fetchUser', moduleType: 'User' },
    { name: 'getUser', moduleType: 'User' },
    { name: 'me', moduleType: 'User' },
    { name: 'searchUser', moduleType: 'User' },
    { name: 'forgotPassword', moduleType: 'User' },
    { name: 'deactivateUser', moduleType: 'User' },
    { name: 'removeUser', moduleType: 'User' },
    { name: 'updateUser', moduleType: 'User' },
    { name: 'updateUserRole', moduleType: 'User' },
    { name: 'createRole', moduleType: 'User' },
    { name: 'updateRole', moduleType: 'User' },
    { name: 'getAllRoles', moduleType: 'User' },
    { name: 'getRole', moduleType: 'User' },
    { name: 'removeRole', moduleType: 'User' },
    { name: 'getUsersWithRoles', moduleType: 'User' },
    { name: 'fetchEmergencyAccessUsers', moduleType: 'User' },
    { name: 'createAppointment', moduleType: 'Appointment' },
    { name: 'createExternalAppointment', moduleType: 'Appointment' },
    { name: 'updateAppointment', moduleType: 'Appointment' },
    { name: 'updateAppointmentBillingStatus', moduleType: 'Appointment' },
    { name: 'findAllAppointments', moduleType: 'Appointment' },
    { name: 'getAppointment', moduleType: 'Appointment' },
    { name: 'getAppointments', moduleType: 'Appointment' },
    { name: 'removeAppointment', moduleType: 'Appointment' },
    { name: 'cancelAppointment', moduleType: 'Appointment' },
    { name: 'getPatientAppointment', moduleType: 'Appointment' },
    { name: 'findAllUpcomingAppointments', moduleType: 'Appointment' },
    { name: 'getPatientPastUpcomingAppointment', moduleType: 'Appointment' },
    { name: 'createFacility', moduleType: 'Facility' },
    { name: 'updateFacility', moduleType: 'Facility' },
    { name: 'updateFacilityTimeZone', moduleType: 'Facility' },
    { name: 'findAllFacility', moduleType: 'Facility' },
    { name: 'getFacility', moduleType: 'Facility' },
    { name: 'removeFacility', moduleType: 'Facility' },
    { name: 'createService', moduleType: 'Services' },
    { name: 'updateService', moduleType: 'Services' },
    { name: 'findAllServices', moduleType: 'Services' },
    { name: 'getService', moduleType: 'Services' },
    { name: 'removeService', moduleType: 'Services' },
    { name: 'createPatient', moduleType: 'Patient' },   
    { name: 'patientInfo', moduleType: 'Patient' },
    { name: 'updatePatientProfile', moduleType: 'Patient' },
    { name: 'sendInviteToPatient', moduleType: 'Patient' },
    { name: 'updatePatientProvider', moduleType: 'Patient' },
    { name: 'findAllPatient', moduleType: 'Patient' },
    { name: 'getPatient', moduleType: 'Patient' },
    { name: 'findPatientAttachments', moduleType: 'Patient' },
    { name: 'fetchAllPatients', moduleType: 'Patient' },
    { name: 'removePatient', moduleType: 'Patient' },
    { name: 'patientInfo', moduleType: 'Patient' },
    { name: 'updatePatient', moduleType: 'Patient' },
    { name: 'updatePatientNoteInfoInputs', moduleType: 'Patient' },
    { name: 'updatePatientProviderRelation', moduleType: 'Patient' },
    { name: 'getPatientProviders', moduleType: 'Patient' },
    { name: 'getPatientProvider', moduleType: 'Patient' },
    { name: 'findAllDoctorPatients', moduleType: 'Patient' },
    { name: 'createPractice', moduleType: 'Practice' },
    { name: 'updatePractice', moduleType: 'Practice' },
    { name: 'findAllPractices', moduleType: 'Practice' },
    { name: 'getPractice', moduleType: 'Practice' },
    { name: 'removePractice', moduleType: 'Practice' },
    { name: 'getPracticesFacilities', moduleType: 'Practice' },
    { name: 'getPracticesUser', moduleType: 'Practice' },
    { name: 'getActiveInactivePractices', moduleType: 'Practice' },
    { name: 'getPracticesByYear', moduleType: 'Practice' },
    { name: 'getPracticeFacilitiesUsersWithRoles', moduleType: 'Practice' },
    { name: 'getPracticeFacilityAppointments', moduleType: 'Practice' },
    { name: 'createDoctor', moduleType: 'Provider' },
    { name: 'updateDoctor', moduleType: 'Provider' },
    { name: 'findAllDoctor', moduleType: 'Provider' },
    { name: 'getDoctor', moduleType: 'Provider' },
    { name: 'removeDoctor', moduleType: 'Provider' },
    { name: 'disableDoctor', moduleType: 'Provider' },
    { name: 'createStaff', moduleType: 'Staff' },
    { name: 'updateStaff', moduleType: 'Staff' },
    { name: 'findAllStaff', moduleType: 'Staff' },
    { name: 'getStaff', moduleType: 'Staff' },
    { name: 'removeStaff', moduleType: 'Staff' },
    { name: 'disableStaff', moduleType: 'Staff' },
    { name: 'createSchedule', moduleType: 'Schedule' },
    { name: 'getDoctorSchedule', moduleType: 'Schedule' },
    { name: 'getFacilitySchedule', moduleType: 'Schedule' },
    { name: 'updateSchedule', moduleType: 'Schedule' },
    { name: 'findAllSchedules', moduleType: 'Schedule' },
    { name: 'getSchedule', moduleType: 'Schedule' },
    { name: 'getSlots', moduleType: 'Schedule' },
    { name: 'removeSchedule', moduleType: 'Schedule' },
    { name: 'addPatientProblem', moduleType: 'Patient Charting' },
    { name: 'updatePatientProblem', moduleType: 'Patient Charting' },
    { name: 'findAllPatientProblem', moduleType: 'Patient Charting' },
    { name: 'searchIcdCodes', moduleType: 'Patient Charting' },
    { name: 'searchSnoMedCodeByIcdCodes', moduleType: 'Patient Charting' },
    { name: 'getPatientProblem', moduleType: 'Patient Charting' },
    { name: 'removePatientProblem', moduleType: 'Patient Charting' },
    { name: 'createPermission', moduleType: 'Permissions' },
    { name: 'assignPermissionToRole', moduleType: 'Permissions' },
    { name: 'updatePermission', moduleType: 'Permissions' },
    { name: 'findAllPermissions', moduleType: 'Permissions' },
    { name: 'GetPermission', moduleType: 'Permissions' },
    { name: 'removePermission', moduleType: 'Permissions' },
    { name: 'addPatientVital', moduleType: 'Patient Charting' },
    { name: 'updatePatientVital', moduleType: 'Patient Charting' },
    { name: 'findAllPatientVitals', moduleType: 'Patient Charting' },
    { name: 'getPatientVital', moduleType: 'Patient Charting' },
    { name: 'removePatientVital', moduleType: 'Patient Charting' },
    { name: 'addPatientAllergy', moduleType: 'Patient Charting' },
    { name: 'updatePatientAllergy', moduleType: 'Patient Charting' },
    { name: 'findAllPatientAllergies', moduleType: 'Patient Charting' },
    { name: 'getPatientAllergy', moduleType: 'Patient Charting' },
    { name: 'removePatientAllergy', moduleType: 'Patient Charting' },
    { name: 'findAllReactions', moduleType: 'Patient Charting' },
    { name: 'findAllAllergies', moduleType: 'Patient Charting' },
    { name: 'createLabTestObservation', moduleType: 'Lab Orders' },
    { name: 'updateLabTestObservation', moduleType: 'Lab Orders' },
    { name: 'removeLabTestObservation', moduleType: 'Lab Orders' },
    { name: 'createLabTest', moduleType: 'Lab Orders' },
    { name: 'updateLabTest', moduleType: 'Lab Orders' },
    { name: 'getLabTest', moduleType: 'Lab Orders' },
    { name: 'findAllLabTest', moduleType: 'Lab Orders' },
    { name: 'removeLabTest', moduleType: 'Agreements' },
    { name: 'createAgreement', moduleType: 'Agreements' },
    { name: 'updateAgreement', moduleType: 'Agreements' },
    { name: 'removeAgreement', moduleType: 'Agreements' },
    { name: 'fetchAgreement', moduleType: 'Agreements' },
    { name: 'fetchAllAgreements', moduleType: 'Agreements' },
    { name: 'getAttachments', moduleType: 'Attachments' },
    { name: 'getAttachmentsByLabOrder', moduleType: 'Attachments' },
    { name: 'getAttachmentsByPolicyId', moduleType: 'Attachments' },
    { name: 'getAttachmentsByAgreementId', moduleType: 'Attachments' },
    { name: 'createAttachmentData', moduleType: 'Attachments' },
    { name: 'removeAttachmentData', moduleType: 'Attachments' },
    { name: 'removeAttachmentMedia', moduleType: 'Attachments' },
    { name: 'updateAttachmentData', moduleType: 'Attachments' },
    { name: 'getAttachment', moduleType: 'Attachments' },
    { name: 'fetchDocumentTypes', moduleType: 'Document Type' },
    { name: 'fetchDocumentType', moduleType: 'Document Type' },
    { name: 'fetchDocumentTypeByName', moduleType: 'Document Type' },
    { name: 'createBilling', moduleType: 'Billing' },
    { name: 'fetchBillingDetailsByAppointmentId', moduleType: 'Billing' },
    { name: 'findAllForms', moduleType: 'Form Builder' },
    { name: 'getForm', moduleType: 'Form Builder' },
    { name: 'findAllUsersForms', moduleType: 'Form Builder' },
    { name: 'createForm', moduleType: 'Form Builder' },
    { name: 'updateForm', moduleType: 'Form Builder' },
    { name: 'removeForm', moduleType: 'Form Builder' },
    { name: 'createFormTemplate', moduleType: 'Form Builder' },
    { name: 'saveUserFormValues', moduleType: 'Form Builder' },
    { name: 'fetchAllPolicies', moduleType: 'Insurance' },
    { name: 'fetchPolicy', moduleType: 'Insurance' },
    { name: 'fetchPatientInsurances', moduleType: 'Insurance' },
    { name: 'createPolicy', moduleType: 'Insurance' },
    { name: 'updatePolicy', moduleType: 'Insurance' },
    { name: 'fetchAllPolicyHolders', moduleType: 'Insurance' },
    { name: 'fetchPolicyHolder', moduleType: 'Insurance' },
    { name: 'createPolicyHolder', moduleType: 'Insurance' },
    { name: 'createPolicyHolder', moduleType: 'Insurance' },
    { name: 'fetchAllInsurances', moduleType: 'Insurance' },
    { name: 'fetchInsurance', moduleType: 'Insurance' },
    { name: 'createCopay', moduleType: 'Insurance' },
    { name: 'findAllTestSpecimenTypes', moduleType: 'Lab Test' },
    { name: 'getSpecimenTypeByName', moduleType: 'Lab Test' },
    { name: 'createLoincCode', moduleType: 'Lab Test' },
    { name: 'updateLoincCode', moduleType: 'Lab Test' },
    { name: 'findAllLoincCodes', moduleType: 'Lab Test' },
    { name: 'findLoincCode', moduleType: 'Lab Test' },
    { name: 'updateLabTestsByOrderNum', moduleType: 'Lab Test' },
    { name: 'findLabTestsByOrderNum', moduleType: 'Lab Test' },
    { name: 'fetchICDCodes', moduleType: 'Lab Test' },

    // Family history

    { name: 'createFamilyHistory', moduleType: 'Patient Charting' },
    { name: 'updateFamilyHistory', moduleType: 'Patient Charting' },
    { name: 'findAllFamilyHistory', moduleType: 'Patient Charting' },

];

export const permissionDataNew = [
    { name: 'findPatientAttachments', moduleType: 'Patient' },
    { name: 'fetchAllPatients', moduleType: 'Patient' },
]

export const practiceAdminPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'updatePatientProvider', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createPractice',
    'updatePractice', 'getPractice', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getFacilitySchedule', 'getDoctorSchedule', 'getSchedule', 'getSlots', 'removeSchedule',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem', 'createPermission', 'assignPermissionToRole',
    'updatePermission', 'findAllPermissions', 'GetPermission', 'removePermission', 'addPatientVital', 'updatePatientVital', 'findAllReactions', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital'
    , 'addPatientAllergy', 'updatePatientAllergy', 'findAllPatientAllergies', 'findAllAllergies', 'getPatientAllergy', 'removePatientAllergy'
    , 'createLabTestObservation', 'updateLabTestObservation', 'removeLabTestObservation', 'createLabTest', 'updateLabTest', 'getLabTest', 'findAllLabTest', 'removeLabTest',
    , 'createAgreement', 'updateAgreement', 'removeAgreement', 'fetchAgreement', 'fetchAllAgreements', 'findAllUpcomingAppointments',
    'getAppointment', 'getAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId',
    'getPracticeFacilitiesUsersWithRoles', 'getPracticeFacilityAppointments', 'getUsersWithRoles', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me', 'fetchEmergencyAccessUsers']

export const facilityAdminPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'updatePatientProvider', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createPractice',
    'updatePractice', 'getPractice', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getFacilitySchedule', 'getDoctorSchedule', 'getSchedule', 'getSlots', 'removeSchedule',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem', 'createPermission', 'assignPermissionToRole',
    'updatePermission', 'findAllPermissions', 'GetPermission', 'removePermission', 'addPatientVital', 'updatePatientVital', 'findAllReactions','findAllPatientVitals', 'getPatientVital', 'removePatientVital',
    'addPatientAllergy', 'updatePatientAllergy', 'findAllPatientAllergies', 'findAllAllergies', 'getPatientAllergy', 'removePatientAllergy', 'createLabTestObservation', 'updateLabTestObservation', 'removeLabTestObservation', 'createLabTest', 'updateLabTest', 'getLabTest', 'findAllLabTest', 'removeLabTest',
    'createAgreement', 'updateAgreement', 'removeAgreement', 'fetchAgreement', 'fetchAllAgreements', 'findAllUpcomingAppointments',
    'getAppointment', 'getAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId',
    'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me', 'fetchEmergencyAccessUsers']

export const emergencyAccessPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'updatePatientProvider', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createPractice',
    'updatePractice', 'getPractice', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getFacilitySchedule', 'getDoctorSchedule', 'getSchedule', 'getSlots', 'removeSchedule',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem', 'createPermission', 'assignPermissionToRole',
    'updatePermission', 'findAllPermissions', 'GetPermission', 'removePermission', 'addPatientVital', 'updatePatientVital', 'findAllReactions', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital',
    'addPatientAllergy', 'updatePatientAllergy', 'findAllPatientAllergies', 'getPatientAllergy', 'removePatientAllergy', 'createLabTestObservation', 'updateLabTestObservation', 'removeLabTestObservation', 'createLabTest', 'updateLabTest', 'getLabTest', 'findAllLabTest', 'removeLabTest',
    'createAgreement', 'updateAgreement', 'removeAgreement', 'fetchAgreement', 'fetchAllAgreements', 'findAllUpcomingAppointments',
    'getAppointment', 'getAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId',
    'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me', 'fetchEmergencyAccessUsers']

export const doctorPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus', 'findAllReactions',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient', 'findAllAllergies', 'getPatientAllergy', 'addPatientAllergy',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule', 'getFacilitySchedule', 'getDoctorSchedule', 'getSlots', 'removeSchedule', 'updatePatientAllergy',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem', , 'addPatientVital', 'updatePatientVital', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital', 'createLabTestObservation', 'updateLabTestObservation', 'removeLabTestObservation', 'createLabTest', 'updateLabTest', 'getLabTest', 'findAllLabTest', 'removeLabTest',
    'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me', 'fetchEmergencyAccessUsers', 'findAllPatientAllergies']

export const nursePermissionsList = ['createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule', 'getFacilitySchedule', 'getDoctorSchedule', 'getSlots', 'removeSchedule',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem', 'addPatientVital', 'updatePatientVital', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital',
    'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me']

export const patientPermissionsList = ['createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule', 'getFacilitySchedule', 'getDoctorSchedule', 'getSlots', 'removeSchedule',
    'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes',
    'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me']

export const staffPermissionsList = ['createPatient', 'updatePatient', 'patientInfo', 'updatePatientProfile',
    'findAllPatient', 'getPatient', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule',
    'getDoctorSlots', 'findAllDoctor', 'getDoctor', 'getStaff', 'updateStaff']

export const practitionerNursePermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule', 'getFacilitySchedule', 'getDoctorSchedule', 'getSlots', 'removeSchedule',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem'
    , 'addPatientVital', 'updatePatientVital', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital', 'addPatientAllergy', 'updatePatientAllergy', 'findAllPatientAllergies', 'findAllAllergies', 'getPatientAllergy', 'removePatientAllergy',
    'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me']

export const officeManagerPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes',
    'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem', 'addPatientVital', 'updatePatientVital', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital',
    'addPatientAllergy', 'updatePatientAllergy', 'findAllPatientAllergies', 'findAllAllergies', 'getPatientAllergy', 'removePatientAllergy'
    , 'createLabTestObservation', 'updateLabTestObservation', 'removeLabTestObservation', 'createLabTest', 'updateLabTest', 'getLabTest', 'findAllLabTest', 'removeLabTest',
    'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me']

export const doctorAssistantPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule', 'getFacilitySchedule', 'getDoctorSchedule', 'getSlots', 'removeSchedule',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem',
    'addPatientVital', 'updatePatientVital', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital', 'addPatientAllergy', 'updatePatientAllergy', 'findAllPatientAllergies', 'findAllAllergies', 'getPatientAllergy', 'removePatientAllergy'
    , 'createLabTestObservation', 'updateLabTestObservation', 'removeLabTestObservation', 'createLabTest', 'updateLabTest', 'getLabTest', 'findAllLabTest', 'removeLabTest',
    'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me']

export const frontDeskPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'updateRole', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment', 'createFacility', 'updateFacility',
    'updateFacilityTimeZone', 'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'sendInviteToPatient', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'createDoctor', 'updateDoctor', 'findAllDoctor', 'getDoctor', 'removeDoctor', 'disableDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'removeStaff', 'disableStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule', 'getFacilitySchedule', 'getDoctorSchedule', 'getSlots', 'removeSchedule',
    'removePatientProblem', 'getPatientProblem', 'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllPatientProblem', 'updatePatientProblem', 'addPatientProblem',
    'addPatientVital', 'updatePatientVital', 'findAllPatientVitals', 'getPatientVital', 'removePatientVital', 'addPatientAllergy', 'updatePatientAllergy', 'findAllPatientAllergies', 'findAllAllergies', 'getPatientAllergy', 'removePatientAllergy'
    , 'createLabTestObservation', 'updateLabTestObservation', 'removeLabTestObservation', 'createLabTest', 'updateLabTest', 'getLabTest', 'findAllLabTest', 'removeLabTest',
    'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'updateLabTestsByOrderNum', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatient', 'updatePatientNoteInfoInputs', 'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me']

    export const billerPermissionsList = ['fetchAllUsers', 'fetchUser', 'getUser', 'searchUser', 'forgotPassword', 'deactivateUser', 'updateUser', 'createRole',
    'updateRole', 'getAllRoles', 'getRole', 'createAppointment', 'createExternalAppointment', 'updateAppointment', 'updateAppointmentBillingStatus',
    'findAllAppointments', 'getAppointment', 'getAppointments', 'cancelAppointment', 'removeAppointment', 'getPatientAppointment',
    'findAllFacility', 'getFacility', 'createService', 'updateService', 'findAllServices', 'getService', 'createPatient',
    'updatePatient', 'patientInfo', 'updatePatientProfile', 'findAllPatient', 'getPatient', 'findPatientAttachments', 'fetchAllPatients', 'findAllDoctor', 'getDoctor', 'createStaff', 'updateStaff',
    'findAllStaff', 'getStaff', 'createSchedule', 'updateSchedule', 'findAllSchedules', 'getSchedule', 'getFacilitySchedule', 'getDoctorSchedule', 'getSlots', 'removeSchedule',
    'searchSnoMedCodeByIcdCodes', 'searchIcdCodes', 'findAllUpcomingAppointments', 'getPatientPastUpcomingAppointment', 'getAttachments', 'getAttachmentsByLabOrder', 'getAttachmentsByPolicyId', 'getAttachmentsByAgreementId',
    'createAttachmentData', 'removeAttachmentData', 'removeAttachmentMedia', 'updateAttachmentData', 'getAttachment', 'fetchDocumentTypes', 'fetchDocumentType',
    'fetchDocumentTypeByName', 'createBilling', 'fetchBillingDetailsByAppointmentId', 'findAllForms', 'getForm', 'findAllUsersForms',
    'createForm', 'updateForm', 'removeForm', 'createFormTemplate', 'saveUserFormValues', 'fetchAllPolicies', 'fetchPolicy', 'fetchPatientInsurances', 'createPolicy',
    'updatePolicy', 'fetchAllPolicyHolders', 'fetchPolicyHolder', 'createPolicyHolder', 'fetchAllInsurances', 'fetchInsurance', 'createCopay', 'findAllTestSpecimenTypes',
    'getSpecimenTypeByName', 'createLoincCode', 'updateLoincCode', 'findAllLoincCodes', 'findLoincCode', 'findLabTestsByOrderNum', 'fetchICDCodes', 'patientInfo',
    'updatePatientProviderRelation', 'getPatient', 'getPatientProviders', 'getPatientProvider', 'findAllDoctorPatients',
    'me']
