import { PracticeType, ServiceCode } from '../../facilities/entities/facility.entity';
import { UserStatus } from '../entities/user.entity';

export const FacilityData = [
    { name: "Private Facility", practiceType: PracticeType.HOSPITAL, code: "+02923", mammographyCertificationNumber: "232232", cliaIdNumber: "023292", federalTaxId: "232232322", isPrivate: true, revenueCode: "323343433", npi: "232332", tamxonomyCode: "2322332", serviceCode: ServiceCode.EMERGENCY_ROOM_23 }];

export const RolesData = [
    { role: 'super-admin', customRole: false },
    { role: 'admin', customRole: false },
    { role: 'doctor', customRole: false },
    { role: 'nurse', customRole: false },
    { role: 'patient', customRole: false },
    { role: 'patient', customRole: false },
    { role: 'staff' , customRole: false},
    { role: 'nurse_practitioner', customRole: false },
    { role: 'office_manager', customRole: false },
    { role: 'doctor_assistant', customRole: false }
];
export const UsersData = [
    { firstName: "Khalid", lastName: "Rasool", password: "super123", email: "khalid.rasool@kwanso.com", status: UserStatus.ACTIVE, phone: "+923426851938", userType: 'super-admin', roleType: 'super-admin', zipCode: "54000", emailVerified: true },
];

export const PermissionData = [
    { name: 'fetchAllUsers' , moduleType: 'User'},
    { name: 'fetchUser' , moduleType: 'User'},
    { name: 'getUser' , moduleType: 'User'},
    { name: 'searchUser' , moduleType: 'User'},
    { name: 'forgotPassword' , moduleType: 'User'},
    { name: 'deactivateUser' , moduleType: 'User'},
    { name: 'removeUser' , moduleType: 'User'},
    { name: 'updateUser' , moduleType: 'User'},
    { name: 'updateRole' , moduleType: 'User'},
    { name: 'createRole' , moduleType: 'User'},
    { name: 'updateRole' , moduleType: 'User'},
    { name: 'getAllRoles' , moduleType: 'User'},
    { name: 'getRole' , moduleType: 'User'},
    { name: 'removeRole' , moduleType: 'User'},
    { name: 'createAppointment' , moduleType: 'Appointment'},
    { name: 'createExternalAppointment' , moduleType: 'Appointment'},
    { name: 'updateAppointment' , moduleType: 'Appointment'},
    { name: 'updateAppointmentBillingStatus' , moduleType: 'Appointment'},
    { name: 'findAllAppointments' , moduleType: 'Appointment'},
    { name: 'getAppointment' , moduleType: 'Appointment'},
    { name: 'getDoctorAppointment', moduleType: 'Appointment' },
    { name: 'removeAppointment' , moduleType: 'Appointment'},
    { name: 'cancelAppointment' , moduleType: 'Appointment'},
    { name: 'getPatientAppointment' , moduleType: 'Appointment'},
    { name: 'createFacility', moduleType: 'Facility' },
    { name: 'updateFacility' , moduleType: 'Facility' },
    { name: 'updateFacilityTimeZone' , moduleType: 'Facility' },
    { name: 'findAllFacility' , moduleType: 'Facility' },
    { name: 'getFacility' , moduleType: 'Facility' },
    { name: 'removeFacility' , moduleType: 'Facility' },
    { name: 'createService' , moduleType: 'Services' },
    { name: 'updateService'  , moduleType: 'Services' },
    { name: 'findAllServices'  , moduleType: 'Services' },
    { name: 'getService'  , moduleType: 'Services' },
    { name: 'removeService'  , moduleType: 'Services' },
    { name: 'createPatient'  , moduleType: 'Patient' },
    { name: 'updatePatient'  , moduleType: 'Patient' },
    { name: 'patientInfo'  , moduleType: 'Patient' },
    { name: 'updatePatientProfile'  , moduleType: 'Patient' },
    { name: 'sendInviteToPatient' , moduleType: 'Patient'  },
    { name: 'updatePatientProvider'  , moduleType: 'Patient' },
    { name: 'findAllPatient'  , moduleType: 'Patient' },
    { name: 'getPatient'  , moduleType: 'Patient' },
    { name: 'removePatient'  , moduleType: 'Patient' },
    { name: 'createPractice'  , moduleType: 'Practice' },
    { name: 'updatePractice'  , moduleType: 'Practice' },
    { name: 'findAllPractices'  , moduleType: 'Practice' },
    { name: 'getPractice'  , moduleType: 'Practice' },
    { name: 'removePractice'  , moduleType: 'Practice' },
    { name: 'createDoctor'  , moduleType: 'Provider' },
    { name: 'updateDoctor'  , moduleType: 'Provider' },
    { name: 'findAllDoctor'  , moduleType: 'Provider' },
    { name: 'getDoctor'  , moduleType: 'Provider' },
    { name: 'removeDoctor'  , moduleType: 'Provider' },
    { name: 'disableDoctor'  , moduleType: 'Provider' },
    { name: 'createStaff'  , moduleType: 'Staff' },
    { name: 'updateStaff'  , moduleType: 'Staff' },
    { name: 'findAllStaff'  , moduleType: 'Staff' },
    { name: 'getStaff'  , moduleType: 'Staff' },
    { name: 'removeStaff'  , moduleType: 'Staff' },
    { name: 'disableStaff'  , moduleType: 'Staff' },
    { name: 'createSchedule'  , moduleType: 'Schedule' },
    { name: 'updateSchedule'  , moduleType: 'Schedule' },
    { name: 'findAllSchedules'  , moduleType: 'Schedules' },
    { name: 'getDoctorSchedule'  , moduleType: 'Schedule' },
    { name: 'getDoctorSlots'  , moduleType: 'Schedule' },
    { name: 'removeSchedule'  , moduleType: 'Schedule' },
    
];
