export const DocumentTypesData = [
  { type: "Audio File" },
  { type: "Audiology" },
  { type: "Authorization" },
  { type: "Bio-Reference Lab Result" },
  { type: "Care Plan" },
  { type: "Chart Note / Archive" },
  { type: "Clinic Paperwork" },
  { type: "Clinical Summary" },
  { type: "Colonoscopy" },
  { type: "Continuity of Care Document" },
  { type: "Continuity of Care Record" },
  { type: "Correspondence" },
  { type: "Disability" },
  { type: "EKGs / Cardiac Diagnostic" },
  { type: "EMG/NCS" },
  { type: "External Record" },
  { type: "Face-sheet" },
  { type: "Health Education Materials" },
  { type: "Hospice Agency Notes" },
  { type: "Hospital records" },
  { type: "Imaging: Bone Density" },
  { type: "Imaging: Mammography" },
  { type: "Immunization" },
  { type: "Informed Consent" },
  { type: "Lab" },
  { type: "LabCorp Lab Result (scanned)" },
  { type: "Legal" },
  { type: "Nursing Agency Notes" },
  { type: "Nursing Certifications" },
  { type: "Other" },
  { type: "Pathology" },
  { type: "Patient Generated" },
  { type: "Patient Image" },
  { type: "Patient Insurance" },
  { type: "Pharmacy" },
  { type: "Pre-op Paperwork" },
  { type: "Quest Lab Result" },
  { type: "Radiology" },
  { type: "Referrals" },
  { type: "Request for medical notes" },
  { type: "Sleep studies" },
  { type: "Sunrise Lab Result" },
  { type: "Therapy" },
  { type: "Ultrasound" },
  { type: "X-Ray" },
]
