import { STATUS } from "src/lib/constants";


const data = [
  {
    mvxCode: "AB",
    manufacturerName: "Abbott Laboratories",
    notes: "includes Ross Products Division, Solvay",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 1,
  },
  {
    mvxCode: "ACA",
    manufacturerName: "Acambis, Inc",
    notes: "acquired by sanofi in sept 2008",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 2,
  },
  {
    mvxCode: "AD",
    manufacturerName: "Adams Laboratories, Inc.",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 3,
  },
  {
    mvxCode: "ALP",
    manufacturerName: "Alpha Therapeutic Corporation",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 4,
  },
  {
    mvxCode: "AR",
    manufacturerName: "Armour",
    notes: "part of CSL",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 5,
  },
  {
    mvxCode: "AVB",
    manufacturerName: "Aventis Behring L.L.C.",
    notes: "part of CSL",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 6,
  },
  {
    mvxCode: "AVI",
    manufacturerName: "Aviron",
    notes: "acquired by Medimmune",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 7,
  },
  {
    mvxCode: "BA",
    manufacturerName: "Baxter Healthcare Corporation-inactive",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 8,
  },
  {
    mvxCode: "BAH",
    manufacturerName: "Baxter Healthcare Corporation",
    notes:
      "includes Hyland Immuno, Immuno International AG,and North American Vaccine, Inc./acquired some assets from alpha therapeutics",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 9,
  },
  {
    mvxCode: "BAY",
    manufacturerName: "Bayer Corporation",
    notes: "Bayer Biologicals now owned by Talecris",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 10,
  },
  {
    mvxCode: "BP",
    manufacturerName: "Berna Products",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 11,
  },
  {
    mvxCode: "BPC",
    manufacturerName: "Berna Products Corporation",
    notes: "includes Swiss Serum and Vaccine Institute Berne",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 12,
  },
  {
    mvxCode: "BTP",
    manufacturerName: "Biotest Pharmaceuticals Corporation",
    notes:
      "New owner of NABI HB as of December 2007, Does NOT replace NABI Biopharmaceuticals in this code list.",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 13,
  },
  {
    mvxCode: "MIP",
    manufacturerName: "Emergent BioSolutions",
    notes:
      "Formerly Emergent BioDefense Operations Lansing and Michigan Biologic Products Institute",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 14,
  },
  {
    mvxCode: "CSL",
    manufacturerName: "bioCSL",
    notes: "bioCSL a part of Seqirus",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "26-Sep-16",
    manufacturer_id: 15,
  },
  {
    mvxCode: "CNJ",
    manufacturerName: "Cangene Corporation",
    notes: "Purchased by Emergent Biosolutions",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "29-Apr-14",
    manufacturer_id: 16,
  },
  {
    mvxCode: "CMP",
    manufacturerName: "Celltech Medeva Pharmaceuticals",
    notes: "Part of Novartis",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 17,
  },
  {
    mvxCode: "CEN",
    manufacturerName: "Centeon L.L.C.",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 18,
  },
  {
    mvxCode: "CHI",
    manufacturerName: "Chiron Corporation",
    notes: "Part of Novartis",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 19,
  },
  {
    mvxCode: "CON",
    manufacturerName: "Connaught",
    notes: "acquired by Merieux",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 21,
  },
  {
    mvxCode: "DVC",
    manufacturerName: "DynPort Vaccine Company, LLC",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 22,
  },
  {
    mvxCode: "EVN",
    manufacturerName: "Evans Medical Limited",
    notes: "Part of Novartis",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 23,
  },
  {
    mvxCode: "GEO",
    manufacturerName: "GeoVax Labs, Inc.",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 24,
  },
  {
    mvxCode: "SKB",
    manufacturerName: "GlaxoSmithKline",
    notes: "includes SmithKline Beecham and Glaxo Wellcome",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 25,
  },
  {
    mvxCode: "GRE",
    manufacturerName: "Greer Laboratories, Inc.",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 26,
  },
  {
    mvxCode: "IAG",
    manufacturerName: "Immuno International AG",
    notes: "Part of Baxter",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 27,
  },
  {
    mvxCode: "IUS",
    manufacturerName: "Immuno-U.S., Inc.",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 28,
  },
  {
    mvxCode: "INT",
    manufacturerName: "Intercell Biomedical",
    notes: "subsidiary of Valneva",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "19-Jul-16",
    manufacturer_id: 29,
  },
  {
    mvxCode: "KGC",
    manufacturerName: "Korea Green Cross Corporation",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 30,
  },
  {
    mvxCode: "LED",
    manufacturerName: "Lederle",
    notes: "became a part of WAL, now owned by Pfizer",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 31,
  },
  {
    mvxCode: "MBL",
    manufacturerName: "Massachusetts Biologic Laboratories",
    notes: "formerly Massachusetts Public Health Biologic Laboratories",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 32,
  },
  {
    mvxCode: "MA",
    manufacturerName: "Massachusetts Public Health Biologic Laboratories",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 33,
  },
  {
    mvxCode: "MED",
    manufacturerName: "MedImmune, Inc. (AstraZeneca)",
    notes: "Subsidiary of AstraZeneca",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "15-May-19",
    manufacturer_id: 34,
  },
  {
    mvxCode: "MSD",
    manufacturerName: "Merck and Co., Inc.",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "18-Oct-12",
    manufacturer_id: 35,
  },
  {
    mvxCode: "IM",
    manufacturerName: "Merieux",
    notes: "Part of sanofi",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 36,
  },
  {
    mvxCode: "MIL",
    manufacturerName: "Miles",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 37,
  },
  {
    mvxCode: "NAB",
    manufacturerName: "NABI",
    notes: "formerly North American Biologicals, Inc.",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 38,
  },
  {
    mvxCode: "NYB",
    manufacturerName: "New York Blood Center",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 39,
  },
  {
    mvxCode: "NAV",
    manufacturerName: "North American Vaccine, Inc.",
    notes: "part of Baxter",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 40,
  },
  {
    mvxCode: "NOV",
    manufacturerName: "Novartis Pharmaceutical Corporation",
    notes:
      "Novartis has sold its flu vaccines to Seqirus and other vaccines to GlaxoSmithKline. While Novartis vaccines may still be in circulation, its mvxStatus is set to not active.",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "13-Apr-16",
    manufacturer_id: 41,
  },
  {
    mvxCode: "NVX",
    manufacturerName: "Novavax, Inc.",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "8-Oct-20",
    manufacturer_id: 42,
  },
  {
    mvxCode: "OTC",
    manufacturerName: "Organon Teknika Corporation",
    notes:
      "Subsidiary of Merck. Sold by Merck 6/8/2021. Effective June 2021  Merck is labeler for BCG product.",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "21-Jul-21",
    manufacturer_id: 43,
  },
  {
    mvxCode: "ORT",
    manufacturerName: "Ortho-clinical Diagnostics",
    notes: "a J & J company (formerly Ortho Diagnostic Systems, Inc.)",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 44,
  },
  {
    mvxCode: "PD",
    manufacturerName: "Parkedale Pharmaceuticals",
    notes: "no website and no news articles (formerly Parke-Davis)",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 45,
  },
  {
    mvxCode: "PWJ",
    manufacturerName: "PowderJect Pharmaceuticals",
    notes: "See Novartis",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 46,
  },
  {
    mvxCode: "PRX",
    manufacturerName: "Praxis Biologics",
    notes: "became a part of WAL, now owned by Pfizer",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 47,
  },
  {
    mvxCode: "JPN",
    manufacturerName:
      "The Research Foundation for Microbial Diseases of Osaka University (BIKEN)",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 48,
  },
  {
    mvxCode: "PMC",
    manufacturerName: "Sanofi Pasteur",
    notes:
      "Formerly Aventis Pasteur, Pasteur Merieux Connaught; includes Connaught Laboratories and Pasteur Merieux. Acquired ACAMBIS; Acquired Protein Sciences (8/28/2017)",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "2-May-19",
    manufacturer_id: 49,
  },
  {
    mvxCode: "SCL",
    manufacturerName: "Sclavo, Inc.",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 50,
  },
  {
    mvxCode: "SOL",
    manufacturerName: "Solvay Pharmaceuticals",
    notes: "Part of Abbott",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 51,
  },
  {
    mvxCode: "SI",
    manufacturerName: "Swiss Serum and Vaccine Inst.",
    notes: "Part of Berna",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 52,
  },
  {
    mvxCode: "TAL",
    manufacturerName: "Talecris Biotherapeutics",
    notes: "includes Bayer Biologicals",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 53,
  },
  {
    mvxCode: "USA",
    manufacturerName:
      "United States Army Medical Research and Material Command",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 54,
  },
  {
    mvxCode: "VXG",
    manufacturerName: "VaxGen",
    notes: "acquired by Emergent Biodefense Operations Lansing, Inc",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 55,
  },
  {
    mvxCode: "WA",
    manufacturerName: "Wyeth-Ayerst",
    notes: "became WAL, now owned by Pfizer",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 56,
  },
  {
    mvxCode: "WAL",
    manufacturerName: "Wyeth",
    notes: "acquired by Pfizer 10/15/2009",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 57,
  },
  {
    mvxCode: "ZLB",
    manufacturerName: "ZLB Behring",
    notes: "acquired by CSL",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 58,
  },
  {
    mvxCode: "OTH",
    manufacturerName: "Other manufacturer",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 59,
  },
  {
    mvxCode: "UNK",
    manufacturerName: "Unknown manufacturer",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "28-May-10",
    manufacturer_id: 60,
  },
  {
    mvxCode: "AKR",
    manufacturerName: "Akorn, Inc",
    notes: "Akorn was a labeler and not a manufacturer",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "19-Apr-17",
    manufacturer_id: 61,
  },
  {
    mvxCode: "PFR",
    manufacturerName: "Pfizer, Inc",
    notes:
      "COVID-19 vaccine in co-development with BioNTech.  Pfizer includes Wyeth-Lederle Vaccines and Pediatrics, Wyeth Laboratories, Lederle Laboratories, and Praxis Biologics",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "30-Oct-20",
    manufacturer_id: 62,
  },
  {
    mvxCode: "BRR",
    manufacturerName: "Barr Laboratories",
    notes: "Subsidiary of Teva Pharmaceuticals",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 64,
  },
  {
    mvxCode: "JNJ",
    manufacturerName: "Johnson and Johnson",
    notes: "acquired CRUCELL which acquired Berna, parent company of Janssen",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "8-Oct-20",
    manufacturer_id: 65,
  },
  {
    mvxCode: "PSC",
    manufacturerName: "Protein Sciences",
    notes: "Acquired by Sanofi Pasteur (08/28/2017)",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "2-May-19",
    manufacturer_id: 66,
  },
  {
    mvxCode: "IDB",
    manufacturerName: "ID Biomedical",
    notes: "Part of GlaxoSmithKline",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 67,
  },
  {
    mvxCode: "GRF",
    manufacturerName: "Grifols",
    notes: "Grifols is a labeler and not a manufacturer.",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "5-Sep-13",
    manufacturer_id: 68,
  },
  {
    mvxCode: "CRU",
    manufacturerName: "Crucell",
    notes: "acquired Berna,  now a J & J company",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 69,
  },
  {
    mvxCode: "KED",
    manufacturerName: "Kedrion Biopharma",
    notes: "acquired Rho(D) from Ortho",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "29-Apr-14",
    manufacturer_id: 70,
  },
  {
    mvxCode: "PAX",
    manufacturerName: "Emergent Travel Health, Inc (Formerly PaxVax)",
    notes:
      "Emergent Biosolutions acquired PaxVax 8/2021, US Vaccines starting to label under Emergent Travel Health Inc.",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "3-Aug-21",
    manufacturer_id: 71,
  },
  {
    mvxCode: "MCM",
    manufacturerName: "MCM Vaccine Company",
    notes: "Partnership between Merck and Sanofi Pasteur",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 72,
  },
  {
    mvxCode: "SEQ",
    manufacturerName: "Seqirus",
    notes:
      "Seqirus acquired the flu vaccines from Novartis. It also includes the CSL vaccines.",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "13-Apr-16",
    manufacturer_id: 73,
  },
  {
    mvxCode: "VAL",
    manufacturerName: "Valneva",
    notes: "Distributes through Intercell in the US",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "19-Jul-16",
    manufacturer_id: 74,
  },
  {
    mvxCode: "DYN",
    manufacturerName: "Dynaport",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "16-Nov-17",
    manufacturer_id: 75,
  },
  {
    mvxCode: "DVX",
    manufacturerName: "Dynavax, Inc.",
    notes: "",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "27-Oct-17",
    manufacturer_id: 76,
  },
  {
    mvxCode: "DSI",
    manufacturerName: "Dispensing Solutions",
    notes: "Vaccine Relabeler",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "10-May-18",
    manufacturer_id: 77,
  },
  {
    mvxCode: "REB",
    manufacturerName: "Rebel Distributors",
    notes: "Vaccine Relabeler",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "10-May-18",
    manufacturer_id: 78,
  },
  {
    mvxCode: "VET",
    manufacturerName: "Vetter Pharma Fertigung GmbH & Co. KG",
    notes: "",
    mvxStatus: STATUS.IN_ACTIVE,
    updateDate: "10-May-18",
    manufacturer_id: 79,
  },
  {
    mvxCode: "TVA",
    manufacturerName: "TEVA Pharmaceuticals USA",
    notes:
      "BARR Laboratories merged with TEVA in 2007.  The MVX for Barr was retired in 2011,  TEVA continues to produce the former BARR vaccines",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "23-Jul-19",
    manufacturer_id: 80,
  },
  {
    mvxCode: "BN",
    manufacturerName: "Bavarian Nordic A/S",
    notes: "manufacturer of national stockpile smallpox vaccine Jynneos",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "17-Jul-20",
    manufacturer_id: 81,
  },
  {
    mvxCode: "MOD",
    manufacturerName: "Moderna US, Inc.",
    notes: "New vaccine manufacturer effective 11/1/2020",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "26-Oct-20",
    manufacturer_id: 90,
  },
  {
    mvxCode: "ASZ",
    manufacturerName: "AstraZeneca",
    notes: "Parent Company of MedImmune",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "30-Oct-20",
    manufacturer_id: 91,
  },
  {
    mvxCode: "JSN",
    manufacturerName: "Janssen",
    notes: "Division of Johnson and Johnson, manufacturer of Covid-19 vaccine",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "26-Oct-20",
    manufacturer_id: 92,
  },
  {
    mvxCode: "SPH",
    manufacturerName: "Sinopharm-Biotech",
    notes: "Non-US COVID-19 Vaccine Manufacturer - WHO Authorized",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "15-Jul-21",
    manufacturer_id: 93,
  },
  {
    mvxCode: "SNV",
    manufacturerName: "Sinovac",
    notes:
      "Non-US COVID-19 Vaccine Manufacturer - WHO Authorized (Sinovac, CoronaVac)",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "12-Jul-21",
    manufacturer_id: 94,
  },
  {
    mvxCode: "MSP",
    manufacturerName:
      "MSP Vaccine Company - (partnership Merck and Sanofi Pasteur)",
    notes:
      "US Based - Joint manufacturing partnership, initial vaccine Vaxelis 10/2020",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "27-Jul-21",
    manufacturer_id: 95,
  },
  {
    mvxCode: "BBI",
    manufacturerName: "Bharat Biotech International Limited",
    notes: "Non-US COVID-19 Vaccine Manufacturer - WHO Authorized (COVAXIN)",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "9-Nov-21",
    manufacturer_id: 96,
  },
  {
    mvxCode: "VBI",
    manufacturerName: "VBI Vaccines, Inc",
    notes: "New Vaccine Manufacturer added 1/2022",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "13-Apr-22",
    manufacturer_id: 97,
  },
  {
    mvxCode: "MDO",
    manufacturerName: "Medicago, Inc",
    notes:
      "Non-US COVID-19 vaccine manufacturer Cofivenz vaccine recognized by ACIP",
    mvxStatus: STATUS.ACTIVE,
    updateDate: "13-Apr-22",
    manufacturer_id: 98,
  },
];

export const mvxData = data?.map(({ manufacturer_id, ...rest }) => ({ ...rest }))