import { AllergyType } from "../entities/allergies.entity"

export const ReactionsData =  [
{ name : "abdominal pain" },
{ name : "anaphylaxis"},
{ name : "angioedema"},
{ name : "arthralgia (joint pain)"},
{ name : "bradycardia"},
{ name : "chest pain"},
{ name : "confusion"},
{ name : "cough"},
{ name : "decreased blood pressure"},
{ name : "diarrhea"},
{ name : "dizziness"},
{ name : "dry mouth"},
{ name : "dyspnea"},
{ name : "edema"},
{ name : "encephalitis"},
{ name : "eye redness"},
{ name : "eye swelling"},
{ name : "facial swelling"},
{ name : "fever"},
{ name : "flushing"},
{ name : "gi bleed"},
{ name : "hair loss"},
{ name : "hallucinations"},
{ name : "headache"},
{ name : "hives"},
{ name : "insomnia"},
{ name : "irregular heart rate"},
{ name : "itching"},
{ name : "lightheadedness"},
{ name : "muscle cramps"},
{ name : "myalgias (muscle pain)"},
{ name : "nausea"},
{ name : "other"},
{ name : "palpitations"},
{ name : "photosensitivity"},
{ name : "rash"},
{ name : "respiratory distress"},
{ name : "ringing in ears"},
{ name : "seizure"},
{ name : "stevens-johnson syndrome"},
{ name : "swelling"},
{ name : "tachycardia"},
{ name : "vasculitis"},
{ name : "vomiting"},
{ name : "wheezing"}
]

export const AllergiesData =  [
{ name : "Pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Animal Dander", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Mite", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Insect", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Latex", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Nickel", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Mold (Inhaled)", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Animal skin cells", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Anthralin", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Animal serum protein", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Animal urine protein", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Arnica extract", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Benzalkonium chloride", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Suture", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Anhydrous lanolin", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Azelaic acid", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Benzalkonium", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Benzethonium", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Benzoic acid", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Benzoyl peroxide", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Benzyl alcohol", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Coal tar", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Floor wax", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Hair dye", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Lanolin", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Methylbenzethonium chloride", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Phenol", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Polycarbonate", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Silk", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Witch hazel", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Wool", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Deer fly bite", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Insect debris", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Clostridium botulinum toxin", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Diphtheria toxin", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Haemophilus antibody", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Microbial antigen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Staphylococcus species antibody", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Streptococcus species antibody", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "3-tree-Pharmacia pollen mix", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "6-grass Pharmacia pollen mix", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Acacia pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Alder pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "American beech pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Ash pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Aster pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Australian pine pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Bahia grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Beech pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Bent grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Bermuda grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Blue-green algae product", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Box elder pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Brome grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cajeput tree pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Canary grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cedar pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Chrysanthemum pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cocklebur pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cocksfoot grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Common pigweed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Common reed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Common sorrel pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cottonwood pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Couch grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cultivated oat pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cultivated rye pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cultivated wheat pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cypress pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Dahlia pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Daisy pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Dandelion pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Dock pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Dog's tail grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Douglas fir pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Elder pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Elm pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "English plantain pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Eucalyptus pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "False ragweed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Fir pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Firebrush pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Flower and weed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Giant ragweed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Golden rod pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Gray elder pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Hazel pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Hop pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Hornbeam pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Italian cypress pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Japanese cedar pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Japanese cypress pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Japanese hop pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Johnson grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "June grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Juniper pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Kentucky blue grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Lamb's quarters pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Lilac pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Lime pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Linden pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Maple pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Meadow fescue pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Meadow foxtail pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Meadow grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Mesquite pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Mugwort pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Nettle pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Oak pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Olive pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Orchard grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Ox-eye daisy pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Palm pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Pecan pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Pellitory pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Pigweed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Pine pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Plane pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Ponderosa pine pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Poplar pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Ragweed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Rape pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Rough marshelder pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Rough pigweed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Russian thistle pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Rye grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Scale pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Scots pine pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Sheep sorrel pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Silver birch pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Snakeweed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Spruce pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Sweet vernal pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Sycamore pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Thistle pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Timothy grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Tree and shrub pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Velvet grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Wall pellitory pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Walnut pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "White ash pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "White pine pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Wild rye grass pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Willow pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Wormwood pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Zea mays pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Ammonium chloride", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cresol and derivatives", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "gamma Benzene hexachloride", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Mercury AND/OR mercury compound", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Molybdenum AND/OR molybdenum compound", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Phthalic acid ester", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Piperonyl butoxide", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Platinum AND/OR platinum compound", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Silicon", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Silk waste", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Silver", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Vanadium AND/OR vanadium compound", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Cat dander", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Dog dander", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Tree pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Weed pollen", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Shampoo", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Bee venom", allergyType: AllergyType.ENVIRONMENT, drugAllergyTypes: ""},
{ name : "Melons, bananas, cucumbers", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Dairy", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Eggs", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Peanuts", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Nuts (not otherwise listed)", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Seafood", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Shellfish", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Soy", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Wheat", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Bakers yeast", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Agar", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Almond oil", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Apple pectin", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Artichoke", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Aspartame", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Eggplant", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Avocado", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Banana", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Beef", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Bilberries", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Blueberries", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Cantaloupe", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Carob", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Carrot", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Chocolate", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Cinnamon", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Citric acid", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Coconut", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Coriander leaf", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Corn oil", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Corn syrup", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Cornflour", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Fish", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Fruit", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Garlic", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Gelatin", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Ginger", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Grapes", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Green beans", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Iodine AND/OR iodine compound", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Kiwi fruit", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Lemons", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Lima beans", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Mineral oil", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Omega 3 fatty acids", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Oats", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Oil of ginger", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Papaya and derivative", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Pectin", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Pepper", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Pepper - seasoning", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Peppermint", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Pork", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Potassium citrate", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Potato", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Poultry", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Protein supplement", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Red kidney beans", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Red Meat", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Root beer", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Rye", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Saccharin", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Seed", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Sesame oil", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Sheep products", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Squash", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Strawberry", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Tomato", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Tryptophan", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Vanilla", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Wheatgerm oil", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Food coloring", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Potassium metabisulfite", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Sodium benzoate", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Sodium metabisulfite", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Sorbic acid", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Sorbitol", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Wine", allergyType: AllergyType.FOOD, drugAllergyTypes: ""}, 
{ name : "Corn", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Soybean (soy protein)", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Egg whites (egg protein)", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Coffee", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Onion", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Gluten", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Dried egg", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Raw egg", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Dried egg white", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Egg yolk", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Egg white", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Hen's egg", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Egg protein", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Egg product", allergyType: AllergyType.FOOD, drugAllergyTypes: ""},
{ name : "Selective Serotonin Reuptake Inhibitors (SSRIs)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Class"},
{ name : "Parabens", allergyType: AllergyType.DRUG, drugAllergyTypes: "Class"},
{ name : "Yellow Dyes (Non-tartrazine)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Class"},
{ name : "Aspartame and Phenylalanine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Class"},
{ name : "Ombitasvir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Class"},
{ name : "Paritaprevir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Class"},
{ name : "Ritonavir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Class"},
{name : "Fluoride Preparations", allergyType: AllergyType.DRUG, drugAllergyTypes: "Inhaled Anesthetics"},
{name : "Heparins", allergyType: AllergyType.DRUG, drugAllergyTypes: "Inhaled Anesthetics"},
{name : "Benzyl Alcohol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Inhaled Anesthetics"},
{name : "Pork-derived Products", allergyType: AllergyType.DRUG, drugAllergyTypes: "Inhaled Anesthetics"},
{name : "LMW Heparin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Inhaled Anesthetics"},
{name : "Methylparaben", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Paroxetine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Propylparaben", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Yellow Dye", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Aspartic Acid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Parabens", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Ombitasvir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Paritaprevir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Ritonavir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Ethylparaben", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Aspartame", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Proparacaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Benzyl Alcohol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Heparin (Porcine)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Enoxaparin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Pork (Porcine) Protein", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "Heparin Flush (Porcine)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Ingredient"},
{name : "PARoxetine HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Methylcellulose", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Cream Base with Liposome", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Benzphetamine HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Mesalamine-Cleanser", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "levETIRAcetam", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Galantamine Hydrobromide", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Salicylic Acid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Imiquimod", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Clindamycin Palmitate HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Adapalene", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Vitamin D (Ergocalciferol)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Vitamin E-Vit A &amp; D", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lidocaine-Hydrocort (Perianal)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lidocaine-Hydrocortisone Ace", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Pramoxine HCl (Perianal)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Metoclopramide HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Triamcinolone Acetonide", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Propylparaben", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Valproic Acid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Neomycin-Polymyxin-Dexameth", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Desonide", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Haloperidol Lactate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Hydrocortisone-Aloe", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Nystatin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "hydrOXYzine HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Nortriptyline HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Dexamethasone", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lidocaine HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Methylparaben", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Aspartame", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "L-Aspartic Acid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Sulfamethoxazole-Trimethoprim", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Heparin Sodium (Porcine)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "fluPHENAZine HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Hyoscyamine Sulfate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Sodium Chloride (Hypertonic)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Fluocinolone Acetonide", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lactic Acid E", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lactic Acid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lidocaine HCl Urethral/Mucosal", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Hydroxocobalamin Acetate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Fluorouracil", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Noni Juice", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Aluminum Hydroxide Gel", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "HYDROmorphone HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Amoxicillin-Pot Clavulanate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Flumazenil", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "levOCARNitine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Citalopram Hydrobromide", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Digoxin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Hormone Cream Base", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Bupivacaine HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Nalbuphine HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lidocaine-EPINEPHrine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Bupivacaine-EPINEPHrine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "clonazePAM", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Cefprozil", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Procainamide HCl", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Neomycin-Polymyxin B GU", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "metroNIDAZOLE", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Lozibase", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Ondansetron", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "HYDROcodone-Acetaminophen", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Benzoyl Peroxide", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Fluticasone Propionate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Enoxaparin Sodium", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Montelukast Sodium", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Dextromethorphan Polistirex ER", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "prednisoLONE Sodium Phosphate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Hydrocortisone", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Sulfacetamide Sodium (Acne)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Carbinoxamine Maleate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Alendronate Sodium", allergyType: AllergyType.DRUG, drugAllergyTypes: "Generic"},
{name : "Paxil", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Hair Skin &amp; Nails Advanced", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Allerwell Allergy Formula", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Neutrogena Healthy Skin SPF15", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Anthelios SX", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Niseko Sunscreen SPF 25", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick UltraSmooth Nourish", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick UltraSmooth Fortify", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick UltraSmooth Soothe", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick UltraSmooth Rejuven", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Avosil", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Viekira Pak", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Udderly Smooth Foot", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Gold Bond Ult Sheer Ribbons", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Keri Overnight", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick True Shimmer", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick Ultra Shimmer", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lip-Care", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Shade UVAGuard SPF15", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pretty Feet/Hands", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Antacid Fast Relief", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aveeno Active Nat Skin Relief", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Elon Skin Repair System", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "VitaMent", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Inova 8/2 Acne Control Therapy", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Inova", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Proteinex P18", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Proteinex-18", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Icy Hot Sleeve", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "NasoGel", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ca-Rezz", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Carbocaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ora-film", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Benefiber Plus Calcium", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tussi-Pres B", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Atralin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Keri Renewal Serum", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Buckleys Cough", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "FortiFense", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lamisilk Repair Complex Serum", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Diuril", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Calaclear", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Calagesic", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Mederma SPF 30", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "A.E.R. Traveler", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pedia-Lax", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Nutra/Pro Strawberry", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Nutra/Pro Chocolate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Nutra/Pro Vanilla", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Zacare", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Castiva Cooling", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Castiva Warming", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pramox", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "LoHist-DM", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Rocaltrol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Gold Bond Medicated Anti Itch", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Restore Cleanser &amp; Moisturizer", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Restore DimethiCreme", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "HurriView", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aspercreme Nighttime", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Gold Bond Foot", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Gold Bond First Aid Quick", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lanacane Maximum Strength", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cortizone-10/Aloe", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Balmex", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cortizone-10 Intensive Healing", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cortizone-10 Plus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Benefiber Drink Mix", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Hydro 40", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Salvax", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tussi-Pres PE Pediatric", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Supress-PE Pediatric", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Mucinex For Kids", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Mucinex Cough For Kids", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Apriso", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Avidoxy DK", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Transdermal Pain Base", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Moi-Stir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Biotene Dry Mouth Moisturizing", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Huggies Diaper Rash", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Capzasin Quick Relief", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Neosalus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Doans PM Extra Strength", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "ProCel", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Arctic Relief Pain Relieving", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "BioGtuss", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Balneol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Blue-Emu Super Strength", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Super E Hand/Body", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick Moisturizer", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Welchol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chantal Sun Screen SPF 30", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick Overnight", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Kerasal Ultra20", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aveeno Creamy Moisturizing", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aveeno Intense Relief", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Biodesp DM", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Differin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Nutra/Shake Fruit Plus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aveeno Ultra-Calming Cleanser", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Urea Hydrating", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Gold Bond Intensive Healing", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "PR Cream", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Wee Care", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Metamucil Fiber", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "P &amp; S", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Vagisil Anti-Itch Medicated", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aveeno Therapeutic", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aveeno Positively Smooth", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Epivir", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ca-Rezz Gentle", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Neutrogena Body", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "ED Bron GP", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Xylocaine/EPINEPHrine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tusicof", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Chapstick Ultra Renewal", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "NoHist-LQ", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "NoHist-DM", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ziagen", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Xylocaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Banzel", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Theraflu Severe Cold &amp; Cough", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "RepHresh", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ed-A-Hist DM", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pres Gen", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pres Gen Pediatric", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Salvax Duo Plus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Fast Freeze Pro Style Therapy", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Rynex PE", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Phoslyra", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "RenaMent", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Odor Free Garlic-X", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Daily Amino 6000", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Sensorcaine/EPINEPHrine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "CEM-Urea", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Zyncof", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tiger Balm Neck &amp; Shoulder Rub", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tiger Balm Arthritis Rub", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "HepaMent", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Dendracin Neurodendraxcin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Desitin Rapid Relief", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Triaminic Cough/Runny Nose", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lexiva", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Nesacaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Sensorcaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Medi-First/Lidocaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Zims Max-Freeze", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Crest Pro-Health Complete", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Colestid Flavored", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Neutrogena On-The-Spot", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ayr Saline Nasal", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Depo-Provera", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Prevalite", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Sorbidon Hydrate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lanacane", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Colestid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Minerin Creme", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cleocin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cleocin-T", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Supress-DX Pediatric", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "PhenylAde Amino Acid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ascriptin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Vibramycin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Benadryl Itch Stopping", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "VCF Vaginal Contraceptive", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aspartame (Nutrasweet)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Clinisol SF", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "DermaZinc Shampoo", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "DermaZinc Cream", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Epivir HBV", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "CellCept", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "PhenylAde", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lidoderm", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Banophen", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Methadose", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "ZyPREXA Zydis", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tineacide", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Estrace", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Prosol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "DelBase Compounding", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Phlexy-10", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Orasep", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Vitamin E &amp; C Beauty Lotion", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tri-Luma", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Complete Amino Acid Mix", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pro-Stat", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lovenox", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Metamucil Smooth Texture", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "ElixSure Cough", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Keppra", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pro-Stat 64", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Kinerase", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Flavor Sweet", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Insta-Glucose", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Listerine PocketPaks", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Grandpas Pine Tar Bath-Shower", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Carafate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Hydromet", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "SPS", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Oracit", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Mouth Kote", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Carnitor", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Calicylic", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "A.E.R. Witch Hazel", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ferretts IPS", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Anti-Itch", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "First-Mouthwash BLM", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Polox", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Gumsol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tussi-Pres", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Tussi-Pres Pediatric", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pearson Sakrin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Quelicin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Baraclude", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ayr Saline Nasal Gel", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Vandazole", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Comfort Shield", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Comfort Clean/Comfort Shield", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "PCCA Sweet-SF", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Marcaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Trimo-San", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Emtriva", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Anbesol Maximum Strength", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Marcaine/Epinephrine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Numoisyn", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Vagisil Maximum Strength", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Metrogel", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Vagisil Feminine Moisturizer", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Zelapar", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Salex", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "MoviPrep", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Claritin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Inova 4/1 Acne Control Therapy", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Questran Light", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "AL12", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ziana", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Carbogel 940", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pro-Stat Sugar Free", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "A+D Cracked Skin Relief", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Os-Cal Extra D3", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Kerr Insta-Char", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Kerr Insta-Char in Sorbitol", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Dritho-Creme HP", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Neutrogena Rainbath", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Carnitor SF", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lamisilk Cleanse", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Maalox", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pro-Stat Profile", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Lip-Guard", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Delsym", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Zyclara", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Aldara", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "BP Wash", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Zyclara Pump", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ovace Plus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Hemorrhoidal", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Prosynminic", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "HPR Plus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pro-Stat Renal Care", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Diabetic Basics Healthy Foot", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Mycocide CX Callus Exfoliator", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pre Protein", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Rosadan", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cardizem", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "MG217 Psoriasis Multi-Symptom", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "MG217 Psoriasis Medicated", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "VH Essentials Medicated", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "VH Essentials Moisturizer", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "VH Essentials Prebiotic", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Alka-Seltzer Plus Cold", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Alka-Seltzer Plus Sinus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Alka-Seltzer Heartburn", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "BenzePrO", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Supress A Pediatric", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Ocean Nasal Moisturizer", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Oasis Moisturizing Mouthwash", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Isentress", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Oasis Moisturizing Mouth Spray", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Oyster Shell Calcium 500+D", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "JointFlex No Mess Roll-On", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cough DM", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "G-Tusicof", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Augmentin ES-600", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Pro-Stat/Fiber", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Eletone", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cortenema", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Moisturizing Skin Protectant", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Skin Protectant", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Synalar", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Synalar (Cream)", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Polocaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Presgen B", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "G-Zyncof", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cutivate", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Cuvposa", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "New Terocin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Prezista", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Zenatane", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Klaron", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Diabet-X Daily Prevention", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Teo-Tus", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Kcentra", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Dometuss-DA/Children", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Locoid", allergyType: AllergyType.DRUG, drugAllergyTypes: "Product"},
{name : "Sonafine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Biafine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Luxamend", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Atopavo", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "AVO Cream", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Huggies Soft Skin", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Proparacaine-Fluorescein", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Gold Bond Ultim Healing Foot", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Aveeno Baby Essential Care", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Remesense", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Ultrasone", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Flucaine", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Bionect", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Nexcare Wound Cleanser", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"},
{name : "Atrapro CP", allergyType: AllergyType.DRUG, drugAllergyTypes: "Medical Supply"}

]