
const data = [
  {
    name: "ACAM2000",
    shortDescription: "vaccinia (smallpox)",
    cvxCode: 75,
    manufacturerName: "Acambis, Inc",
    mvxCode: "ACA",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "28-May-10",
  },
  {
    name: "ACAM2000",
    shortDescription: "vaccinia (smallpox)",
    cvxCode: 75,
    manufacturerName: "Emergent BioSolutions",
    mvxCode: "MIP",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Jun-22",
  },
  {
    name: "ACEL-IMUNE",
    shortDescription: "DTaP",
    cvxCode: 20,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "ACTHIB",
    shortDescription: "Hib (PRP-T)",
    cvxCode: 48,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "ADACEL",
    shortDescription: "Tdap",
    cvxCode: 115,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "Adenovirus types 4 and 7",
    shortDescription: "Adenovirus types 4 and 7",
    cvxCode: 143,
    manufacturerName: "TEVA Pharmaceuticals USA",
    mvxCode: "TVA",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "23-Jul-19",
  },
  {
    name: "Adenovirus types 4 and 7",
    shortDescription: "Adenovirus types 4 and 7",
    cvxCode: 143,
    manufacturerName: "Barr Laboratories",
    mvxCode: "BRR",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "30-Jul-19",
  },
  {
    name: "Afluria",
    shortDescription: "Influenza, seasonal, injectable",
    cvxCode: 141,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "26-Sep-16",
  },
  {
    name: "AFLURIA",
    shortDescription: "Influenza, seasonal, injectable",
    cvxCode: 141,
    manufacturerName: "bioCSL",
    mvxCode: "CSL",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "26-Sep-16",
  },
  {
    name: "Afluria quadrivalent preservative free",
    shortDescription: "influenza, injectable, quadrivalent, preservative free",
    cvxCode: 150,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "4-Oct-16",
  },
  {
    name: "Afluria quadrivalent, preservative free, pediatric",
    shortDescription:
      "Influenza, injectable,quadrivalent, preservative free, pediatric",
    cvxCode: 161,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "26-Aug-19",
  },
  {
    name: "Afluria, preservative free",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "26-Sep-16",
  },
  {
    name: "Afluria, preservative free",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "bioCSL",
    mvxCode: "CSL",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "26-Sep-16",
  },
  {
    name: "Afluria, quadrivalent",
    shortDescription: "influenza, injectable, quadrivalent",
    cvxCode: 158,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "4-Oct-16",
  },
  {
    name: "AGRIFLU",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "15-Nov-17",
  },
  {
    name: "AS03 adjuvant",
    shortDescription: "AS03 Adjuvant",
    cvxCode: 801,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "11-Sep-15",
  },
  {
    name: "AstraZeneca COVID-19 Vaccine (Non-US tradenames include VAXZEVRIA, COVISHIELD)",
    shortDescription: "COVID-19 vaccine, vector-nr, rS-ChAdOx1, PF, 0.5 mL",
    cvxCode: 210,
    manufacturerName: "AstraZeneca",
    mvxCode: "ASZ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "ATTENUVAX",
    shortDescription: "measles",
    cvxCode: 5,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "28-Apr-15",
  },
  {
    name: "Bexsero",
    shortDescription: "meningococcal B, OMV",
    cvxCode: 163,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Active",
    updateDate: "2-Feb-15",
  },
  {
    name: "Bexsero",
    shortDescription: "meningococcal B, OMV",
    cvxCode: 163,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "22-Mar-16",
  },
  {
    name: "BIAVAX II",
    shortDescription: "rubella/mumps",
    cvxCode: 38,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "BIOTHRAX",
    shortDescription: "anthrax",
    cvxCode: 24,
    manufacturerName: "Emergent BioSolutions",
    mvxCode: "MIP",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "BOOSTRIX",
    shortDescription: "Tdap",
    cvxCode: 115,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "CERTIVA",
    shortDescription: "DTaP",
    cvxCode: 20,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "CERVARIX",
    shortDescription: "HPV, bivalent",
    cvxCode: 118,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "22-Nov-16",
  },
  {
    name: "COMIRNATY",
    shortDescription: "COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose",
    cvxCode: 208,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "18-May-22",
  },
  {
    name: "COMIRNATY",
    shortDescription:
      "COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose, tris-sucrose",
    cvxCode: 217,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "18-May-22",
  },
  {
    name: "COMVAX",
    shortDescription: "Hib-Hep B",
    cvxCode: 51,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "11-Mar-16",
  },
  {
    name: "Coronavac (Sinovac) COVID-19 Vaccine",
    shortDescription: "COVID-19 IV Non-US Vaccine (CoronaVac, Sinovac)",
    cvxCode: 511,
    manufacturerName: "Sinovac",
    mvxCode: "SNV",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "COVAXIN (Bharat) COVID-19 Vaccine",
    shortDescription: "COVID-19 IV Non-US Vaccine (COVAXIN)",
    cvxCode: 502,
    manufacturerName: "Bharat Biotech International Limited",
    mvxCode: "BBI",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Nov-21",
  },
  {
    name: "Covifenz",
    shortDescription:
      "SARS-COV-2 COVID-19 VLP Non-US Vaccine (Medicago, Covifenz)",
    cvxCode: 512,
    manufacturerName: "Medicago, Inc",
    mvxCode: "MDO",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "11-Apr-22",
  },
  {
    name: "DAPTACEL",
    shortDescription: "DTaP, 5 pertussis antigens",
    cvxCode: 106,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "DECAVAC",
    shortDescription:
      "Td (adult), 5 Lf tetanus toxoid, preservative free, adsorbed",
    cvxCode: 113,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "27-Oct-17",
  },
  {
    name: "DENGVAXIA",
    shortDescription: "dengue fever",
    cvxCode: 56,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "4-Sep-19",
  },
  {
    name: "DRYVAX",
    shortDescription: "vaccinia (smallpox)",
    cvxCode: 75,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "DT(GENERIC)",
    shortDescription: "DT (pediatric)",
    cvxCode: 28,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "ENGERIX B-PEDS",
    shortDescription: "Hep B, adolescent or pediatric",
    cvxCode: 8,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "ENGERIX-B-ADULT",
    shortDescription: "Hep B, adult",
    cvxCode: 43,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "ERVEBO (Ebola Zaire Vaccine, Live)",
    shortDescription: "Ebola Zaire vaccine, live, recombinant, 1mL dose",
    cvxCode: 204,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "23-Mar-21",
  },
  {
    name: "Fluad",
    shortDescription: "influenza, trivalent, adjuvanted",
    cvxCode: 168,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-16",
  },
  {
    name: "Fluad",
    shortDescription: "influenza, trivalent, adjuvanted",
    cvxCode: 168,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Active",
    updateDate: "9-Aug-16",
  },
  {
    name: "FLUAD Quadrivalent",
    shortDescription: "Influenza vaccine, quadrivalent, adjuvanted",
    cvxCode: 205,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "20-Jul-20",
  },
  {
    name: "FLUARIX",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "27-Sep-10",
  },
  {
    name: "Fluarix, quadrivalent, preservative free",
    shortDescription: "influenza, injectable, quadrivalent, preservative free",
    cvxCode: 150,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "Flublok",
    shortDescription: "influenza, recombinant, injectable, preservative free",
    cvxCode: 155,
    manufacturerName: "Protein Sciences",
    mvxCode: "PSC",
    mvxStatus: "Inactive",
    status: "Active",
    updateDate: "28-May-13",
  },
  {
    name: "Flublok quadrivalent",
    shortDescription:
      "influenza, recombinant, quadrivalent,injectable, preservative free",
    cvxCode: 185,
    manufacturerName: "Protein Sciences",
    mvxCode: "PSC",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "2-May-19",
  },
  {
    name: "Flublok quadrivalent",
    shortDescription:
      "influenza, recombinant, quadrivalent,injectable, preservative free",
    cvxCode: 185,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "2-May-19",
  },
  {
    name: "Flucelvax",
    shortDescription: "Influenza, injectable, MDCK, preservative free",
    cvxCode: 153,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "24-Jun-16",
  },
  {
    name: "flucelvax, quadrivalent, preservative free",
    shortDescription:
      "Influenza, injectable, MDCK, preservative free, quadrivalent",
    cvxCode: 171,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "16-Jun-16",
  },
  {
    name: "Flucelvax, quadrivalent, with preservative",
    shortDescription: "Influenza, injectable, MDCK, quadrivalent, preservative",
    cvxCode: 186,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "27-Jun-17",
  },
  {
    name: "FLULAVAL",
    shortDescription: "Influenza, seasonal, injectable",
    cvxCode: 141,
    manufacturerName: "ID Biomedical",
    mvxCode: "IDB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-13",
  },
  {
    name: "Flulaval quadrivalent",
    shortDescription: "influenza, injectable, quadrivalent",
    cvxCode: 158,
    manufacturerName: "ID Biomedical",
    mvxCode: "IDB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-13",
  },
  {
    name: "Flulaval, preservative free",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "ID Biomedical",
    mvxCode: "IDB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "5-Jun-17",
  },
  {
    name: "Flulaval, quadrivalent, preservative free",
    shortDescription: "influenza, injectable, quadrivalent, preservative free",
    cvxCode: 150,
    manufacturerName: "ID Biomedical",
    mvxCode: "IDB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "21-Oct-14",
  },
  {
    name: "FLUMIST",
    shortDescription: "influenza, live, intranasal",
    cvxCode: 111,
    manufacturerName: "MedImmune, Inc. (AstraZeneca)",
    mvxCode: "MED",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "23-Oct-15",
  },
  {
    name: "Flumist quadrivalent",
    shortDescription: "influenza, live, intranasal, quadrivalent",
    cvxCode: 149,
    manufacturerName: "MedImmune, Inc. (AstraZeneca)",
    mvxCode: "MED",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "7-Aug-12",
  },
  {
    name: "FLUVIRIN",
    shortDescription: "Influenza, seasonal, injectable",
    cvxCode: 141,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Active",
    updateDate: "27-Sep-10",
  },
  {
    name: "Fluvirin",
    shortDescription: "Influenza, seasonal, injectable",
    cvxCode: 141,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "12-Jun-17",
  },
  {
    name: "Fluvirin preservative free",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "Seqirus",
    mvxCode: "SEQ",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "12-Jun-17",
  },
  {
    name: "FLUVIRIN-PRESERVATIVE FREE",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "FLUZONE",
    shortDescription: "Influenza, seasonal, injectable",
    cvxCode: 141,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "27-Sep-10",
  },
  {
    name: "FLUZONE High-Dose Quadrivalent",
    shortDescription: "influenza, high-dose, quadrivalent",
    cvxCode: 197,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "29-Jan-20",
  },
  {
    name: "Fluzone Quad Intradermal",
    shortDescription: "influenza, intradermal, quadrivalent, preservative free",
    cvxCode: 166,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "15-Dec-14",
  },
  {
    name: "FLUZONE Quadrivalent Southern Hemisphere",
    shortDescription: "influenza, Southern Hemisphere, preservative free",
    cvxCode: 201,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "12-Mar-20",
  },
  {
    name: "FLUZONE Quadrivalent Southern Hemisphere",
    shortDescription:
      "influenza, Southern Hemisphere, quadrivalent, with preservative",
    cvxCode: 202,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "12-Mar-20",
  },
  {
    name: "FLUZONE Quadrivalent Southern Hemisphere, Pediatric",
    shortDescription:
      "influenza, Southern Hemisphere, pediatric, preservative free",
    cvxCode: 200,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "21-Apr-20",
  },
  {
    name: "Fluzone Quadrivalent, pediatric",
    shortDescription:
      "Influenza, injectable,quadrivalent, preservative free, pediatric",
    cvxCode: 161,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "23-Jul-14",
  },
  {
    name: "Fluzone, intradermal",
    shortDescription: "influenza, seasonal, intradermal, preservative free",
    cvxCode: 144,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "Fluzone, Quadrivalent",
    shortDescription: "influenza, injectable, quadrivalent",
    cvxCode: 158,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "8-Aug-13",
  },
  {
    name: "Fluzone, quadrivalent, preservative free",
    shortDescription: "influenza, injectable, quadrivalent, preservative free",
    cvxCode: 150,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "21-Oct-14",
  },
  {
    name: "FLUZONE-HIGH DOSE",
    shortDescription: "Influenza, high dose seasonal",
    cvxCode: 135,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "FLUZONE-PRESERVATIVE FREE",
    shortDescription: "Influenza, seasonal, injectable, preservative free",
    cvxCode: 140,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "GARDASIL",
    shortDescription: "HPV, quadrivalent",
    cvxCode: 62,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "28-May-10",
  },
  {
    name: "Gardasil 9",
    shortDescription: "HPV9",
    cvxCode: 165,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "11-Dec-14",
  },
  {
    name: "HAVRIX-ADULT",
    shortDescription: "Hep A, adult",
    cvxCode: 52,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "HAVRIX-PEDS",
    shortDescription: "Hep A, ped/adol, 2 dose",
    cvxCode: 83,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "HEPLISAV-B",
    shortDescription: "HepB-CpG",
    cvxCode: 189,
    manufacturerName: "Dynavax, Inc.",
    mvxCode: "DVX",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "27-Oct-17",
  },
  {
    name: "HIBERIX",
    shortDescription: "Hib (PRP-T)",
    cvxCode: 48,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "HIBTITER",
    shortDescription: "Hib (HbOC)",
    cvxCode: 47,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "18-Aug-10",
  },
  {
    name: "Imovax",
    shortDescription: "rabies, intramuscular injection",
    cvxCode: 18,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "12-Dec-16",
  },
  {
    name: "IMOVAX",
    shortDescription: "Rabies - IM Diploid cell culture",
    cvxCode: 175,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "19-Oct-16",
  },
  {
    name: "IMOVAX ID",
    shortDescription: "rabies, intradermal injection",
    cvxCode: 40,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "22-Nov-16",
  },
  {
    name: "INFANRIX",
    shortDescription: "DTaP",
    cvxCode: 20,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "Influenza A (H5N1) -2013",
    shortDescription: "Influenza A monovalent (H5N1), ADJUVANTED-2013",
    cvxCode: 160,
    manufacturerName: "ID Biomedical",
    mvxCode: "IDB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "16-Jan-14",
  },
  {
    name: "Influenza A monovalent (H5N1), ADJUVANTED-2013",
    shortDescription: "Influenza A monovalent (H5N1), ADJUVANTED-2013",
    cvxCode: 160,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "IPOL",
    shortDescription: "IPV",
    cvxCode: 10,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "IXIARO",
    shortDescription: "Japanese Encephalitis IM",
    cvxCode: 134,
    manufacturerName: "Intercell Biomedical",
    mvxCode: "INT",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "19-Jul-16",
  },
  {
    name: "Ixiaro",
    shortDescription: "Japanese Encephalitis IM",
    cvxCode: 134,
    manufacturerName: "Valneva",
    mvxCode: "VAL",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "19-Jul-16",
  },
  {
    name: "IXIARO",
    shortDescription: "Japanese Encephalitis IM",
    cvxCode: 134,
    manufacturerName: "Vetter Pharma Fertigung GmbH & Co. KG",
    mvxCode: "VET",
    mvxStatus: "Inactive",
    status: "Active",
    updateDate: "4-Dec-17",
  },
  {
    name: "Janssen (J&J) COVID-19 Vaccine",
    shortDescription: "COVID-19 vaccine, vector-nr, rS-Ad26, PF, 0.5 mL",
    cvxCode: 212,
    manufacturerName: "Janssen",
    mvxCode: "JSN",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "12-Jul-21",
  },
  {
    name: "JE-VAX",
    shortDescription: "Japanese encephalitis SC",
    cvxCode: 39,
    manufacturerName:
      "The Research Foundation for Microbial Diseases of Osaka University (BIKEN)",
    mvxCode: "JPN",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "29-Apr-15",
  },
  {
    name: "JYNNEOS",
    shortDescription:
      "Vaccinia, smallpox monkeypox vaccine live, PF, SQ or ID injection",
    cvxCode: 206,
    manufacturerName: "Bavarian Nordic A/S",
    mvxCode: "BN",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "20-May-22",
  },
  {
    name: "KINRIX",
    shortDescription: "DTaP-IPV",
    cvxCode: 130,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "MENACTRA",
    shortDescription: "meningococcal MCV4P",
    cvxCode: 114,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "MENHIBRIX",
    shortDescription: "Meningococcal C/Y-HIB PRP",
    cvxCode: 148,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "15-Nov-17",
  },
  {
    name: "MENOMUNE",
    shortDescription: "meningococcal MPSV4",
    cvxCode: 32,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "27-Oct-17",
  },
  {
    name: "MenQuadfi",
    shortDescription:
      "meningococcal polysaccharide (groups A, C, Y, W-135) TT conjugate",
    cvxCode: 203,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "27-May-20",
  },
  {
    name: "Menveo",
    shortDescription: "Meningococcal MCV4O",
    cvxCode: 136,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "22-Mar-16",
  },
  {
    name: "MENVEO",
    shortDescription: "Meningococcal MCV4O",
    cvxCode: 136,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Active",
    updateDate: "22-Mar-16",
  },
  {
    name: "MERUVAX II",
    shortDescription: "rubella",
    cvxCode: 6,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "28-Apr-15",
  },
  {
    name: "M-M-R II",
    shortDescription: "MMR",
    cvxCode: 3,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "Moderna COVID-19 Vaccine (non-US Spikevax)",
    shortDescription: "COVID-19, mRNA, LNP-S, PF, 50 mcg/0.5 mL dose",
    cvxCode: 221,
    manufacturerName: "Moderna US, Inc.",
    mvxCode: "MOD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "Moderna COVID-19 Vaccine (non-US Spikevax)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, PF, pediatric 25 mcg/0.25 mL dose",
    cvxCode: 228,
    manufacturerName: "Moderna US, Inc.",
    mvxCode: "MOD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "Moderna COVID-19 Vaccine (non-US Spikevax)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, bivalent booster, PF, 50 mcg/0.5 mL or 25mcg/0.25 mL dose",
    cvxCode: 229,
    manufacturerName: "Moderna US, Inc.",
    mvxCode: "MOD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "Moderna COVID-19 Vaccine (non-US Spikevax)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, PF, 100 mcg/0.5mL dose or 50 mcg/0.25mL dose",
    cvxCode: 207,
    manufacturerName: "Moderna US, Inc.",
    mvxCode: "MOD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "Moderna COVID-19 Vaccine (non-US Spikevax)",
    shortDescription: "COVID-19, mRNA, LNP-S, PF, pediatric 50 mcg/0.5 mL dose",
    cvxCode: 227,
    manufacturerName: "Moderna US, Inc.",
    mvxCode: "MOD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "MUMPSVAX",
    shortDescription: "mumps",
    cvxCode: 7,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "MYCOBAX",
    shortDescription: "BCG",
    cvxCode: 19,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "11-Dec-15",
  },
  {
    name: "Novavax COVID-19 Vaccine",
    shortDescription:
      "COVID-19, subunit, rS-nanoparticle+Matrix-M1 Adjuvant, PF, 0.5 mL",
    cvxCode: 211,
    manufacturerName: "Novavax, Inc.",
    mvxCode: "NVX",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "23-Mar-21",
  },
  {
    name: "Novel influenza-H1N1-09",
    shortDescription: "Novel influenza-H1N1-09",
    cvxCode: 127,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "Novel influenza-H1N1-09",
    shortDescription: "Novel influenza-H1N1-09",
    cvxCode: 127,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "Novel influenza-H1N1-09",
    shortDescription: "Novel influenza-H1N1-09",
    cvxCode: 127,
    manufacturerName: "bioCSL",
    mvxCode: "CSL",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "Novel Influenza-H1N1-09, nasal",
    shortDescription: "Novel Influenza-H1N1-09, nasal",
    cvxCode: 125,
    manufacturerName: "MedImmune, Inc. (AstraZeneca)",
    mvxCode: "MED",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "Novel influenza-H1N1-09, preservative-free",
    shortDescription: "Novel influenza-H1N1-09, preservative-free",
    cvxCode: 126,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "Novel influenza-H1N1-09, preservative-free",
    shortDescription: "Novel influenza-H1N1-09, preservative-free",
    cvxCode: 126,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "Novel influenza-H1N1-09, preservative-free",
    shortDescription: "Novel influenza-H1N1-09, preservative-free",
    cvxCode: 126,
    manufacturerName: "bioCSL",
    mvxCode: "CSL",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "27-Aug-15",
  },
  {
    name: "OMNIHIB",
    shortDescription: "Hib (PRP-T)",
    cvxCode: 48,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "ORIMUNE",
    shortDescription: "OPV",
    cvxCode: 2,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "PEDIARIX",
    shortDescription: "DTaP-Hep B-IPV",
    cvxCode: 110,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "PEDVAXHIB",
    shortDescription: "Hib (PRP-OMP)",
    cvxCode: 49,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "PENTACEL",
    shortDescription: "DTaP-Hib-IPV",
    cvxCode: 120,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "Pfizer-BioNTech COVID-19 Vaccine (EUA labeled)  COMIRNATY (BLA labeled)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose, tris-sucrose",
    cvxCode: 217,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-21",
  },
  {
    name: "Pfizer-BioNTech COVID-19 Vaccine (EUA labeled)  COMIRNATY (BLA labeled)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, bivalent booster, PF, 10 mcg/0.2 mL dose",
    cvxCode: 301,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-21",
  },
  {
    name: "Pfizer-BioNTech COVID-19 Vaccine (EUA labeled)  COMIRNATY (BLA labeled)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, PF, 10 mcg/0.2 mL dose, tris-sucrose",
    cvxCode: 218,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-21",
  },
  {
    name: "Pfizer-BioNTech COVID-19 Vaccine (EUA labeled)  COMIRNATY (BLA labeled)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, PF, 3 mcg/0.2 mL dose, tris-sucrose",
    cvxCode: 219,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-21",
  },
  {
    name: "Pfizer-BioNTech COVID-19 Vaccine (EUA labeled)  COMIRNATY (BLA labeled)",
    shortDescription:
      "COVID-19, mRNA, LNP-S, bivalent booster, PF, 30 mcg/0.3 mL dose",
    cvxCode: 300,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-21",
  },
  {
    name: "Pfizer-BioNTech COVID-19 Vaccine (EUA labeled)  COMIRNATY (BLA labeled)",
    shortDescription: "COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose",
    cvxCode: 208,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Sep-21",
  },
  {
    name: "PNEUMOVAX 23",
    shortDescription: "pneumococcal polysaccharide PPV23",
    cvxCode: 33,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "PREHEVBRIO Hepatitis B Vaccine (Recombinant)",
    shortDescription: "HepB recombinant, 3-antigen, Al(OH)3",
    cvxCode: 220,
    manufacturerName: "VBI Vaccines, Inc",
    mvxCode: "VBI",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "25-Jan-22",
  },
  {
    name: "PREVNAR 13",
    shortDescription: "Pneumococcal conjugate PCV 13",
    cvxCode: 133,
    manufacturerName: "Wyeth",
    mvxCode: "WAL",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "28-May-10",
  },
  {
    name: "PREVNAR 13",
    shortDescription: "Pneumococcal conjugate PCV 13",
    cvxCode: 133,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "PREVNAR 20",
    shortDescription:
      "Pneumococcal conjugate PCV20, polysaccharide CRM197 conjugate, adjuvant, PF",
    cvxCode: 216,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "18-Aug-21",
  },
  {
    name: "PREVNAR 7",
    shortDescription: "pneumococcal conjugate PCV 7",
    cvxCode: 100,
    manufacturerName: "Wyeth",
    mvxCode: "WAL",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "24-Sep-15",
  },
  {
    name: "PREVNAR 7",
    shortDescription: "pneumococcal conjugate PCV 7",
    cvxCode: 100,
    manufacturerName: "Wyeth",
    mvxCode: "WAL",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "24-Sep-15",
  },
  {
    name: "Priorix",
    shortDescription: "MMR",
    cvxCode: 3,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "15-Jun-22",
  },
  {
    name: "PROHIBIT",
    shortDescription: "Hib (PRP-D)",
    cvxCode: 46,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "PROQUAD",
    shortDescription: "MMRV",
    cvxCode: 94,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "Quadracel",
    shortDescription: "DTaP-IPV",
    cvxCode: 130,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "26-Mar-15",
  },
  {
    name: "RABAVERT",
    shortDescription: "Rabies - IM fibroblast culture",
    cvxCode: 176,
    manufacturerName: "Novartis Pharmaceutical Corporation",
    mvxCode: "NOV",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "19-Oct-16",
  },
  {
    name: "RABAVERT",
    shortDescription: "Rabies - IM fibroblast culture",
    cvxCode: 176,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "19-Oct-16",
  },
  {
    name: "RabAvert",
    shortDescription: "rabies, intramuscular injection",
    cvxCode: 18,
    manufacturerName: "Chiron Corporation",
    mvxCode: "CHI",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "22-Mar-16",
  },
  {
    name: "RECOMBIVAX-ADULT",
    shortDescription: "Hep B, adult",
    cvxCode: 43,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "RECOMBIVAX-DIALYSIS",
    shortDescription: "Hep B, dialysis",
    cvxCode: 44,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "RECOMBIVAX-PEDS",
    shortDescription: "Hep B, adolescent or pediatric",
    cvxCode: 8,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "ROTARIX",
    shortDescription: "rotavirus, monovalent",
    cvxCode: 119,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "ROTATEQ",
    shortDescription: "rotavirus, pentavalent",
    cvxCode: 116,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "Sanofi COVID-19",
    shortDescription:
      "COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 5mcg/0.5mL",
    cvxCode: 225,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Mar-22",
  },
  {
    name: "Sanofi COVID-19",
    shortDescription:
      "COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 10mcg/0.5mL",
    cvxCode: 226,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "10-Mar-22",
  },
  {
    name: "SHINGRIX",
    shortDescription: "zoster recombinant",
    cvxCode: 187,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "27-Oct-17",
  },
  {
    name: "Sinopharm (BIBP) COVID-19 Vaccine",
    shortDescription: "COVID-19 IV Non-US Vaccine (BIBP, Sinopharm)",
    cvxCode: 510,
    manufacturerName: "Sinopharm-Biotech",
    mvxCode: "SPH",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "13-Jul-21",
  },
  {
    name: "SPIKEVAX",
    shortDescription:
      "COVID-19, mRNA, LNP-S, PF, 100 mcg/0.5mL dose or 50 mcg/0.25mL dose",
    cvxCode: 207,
    manufacturerName: "Moderna US, Inc.",
    mvxCode: "MOD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "18-May-22",
  },
  {
    name: "Stamaril",
    shortDescription: "Yellow fever vaccine - alt",
    cvxCode: 183,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "2-Mar-17",
  },
  {
    name: "Td, adsorbed",
    shortDescription:
      "Td (adult), 2 Lf tetanus toxoid, preservative free, adsorbed",
    cvxCode: 9,
    manufacturerName: "Massachusetts Biologic Laboratories",
    mvxCode: "MBL",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "21-May-19",
  },
  {
    name: "Td, adsorbed",
    shortDescription:
      "Td (adult), 2 Lf tetanus toxoid, preservative free, adsorbed",
    cvxCode: 9,
    manufacturerName: "Grifols",
    mvxCode: "GRF",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "21-May-19",
  },
  {
    name: "TDVAX",
    shortDescription:
      "Td (adult), 2 Lf tetanus toxoid, preservative free, adsorbed",
    cvxCode: 9,
    manufacturerName: "Massachusetts Biologic Laboratories",
    mvxCode: "MBL",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "21-May-19",
  },
  {
    name: "Tenivac",
    shortDescription:
      "Td (adult), 5 Lf tetanus toxoid, preservative free, adsorbed",
    cvxCode: 113,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "TETANUS TOXOID (GENERIC)",
    shortDescription: "tetanus toxoid, adsorbed",
    cvxCode: 35,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "28-May-10",
  },
  {
    name: "TETRAMUNE",
    shortDescription: "DTP-Hib",
    cvxCode: 22,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "1-Sep-10",
  },
  {
    name: "TICE BCG",
    shortDescription: "BCG",
    cvxCode: 19,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "26-Jul-21",
  },
  {
    name: "TICOVAC",
    shortDescription: "Tick-borne encephalitis, inactivated, PF, 0.5mL",
    cvxCode: 224,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "4-Nov-21",
  },
  {
    name: "TICOVAC",
    shortDescription: "Tick-borne encephalitis, inactivated, PF, 0.25mL",
    cvxCode: 223,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "4-Nov-21",
  },
  {
    name: "TRIHIBIT",
    shortDescription: "DTaP-Hib",
    cvxCode: 50,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "21-Mar-17",
  },
  {
    name: "TRIPEDIA",
    shortDescription: "DTaP",
    cvxCode: 20,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Inactive",
    updateDate: "15-Nov-17",
  },
  {
    name: "Trumenba",
    shortDescription: "meningococcal B, recombinant",
    cvxCode: 162,
    manufacturerName: "Pfizer, Inc",
    mvxCode: "PFR",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "3-Nov-14",
  },
  {
    name: "TWINRIX",
    shortDescription: "Hep A-Hep B",
    cvxCode: 104,
    manufacturerName: "GlaxoSmithKline",
    mvxCode: "SKB",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "TYPHIM VI",
    shortDescription: "typhoid, ViCPs",
    cvxCode: 101,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "TYPHOID-AKD",
    shortDescription: "typhoid, parenteral, AKD (U.S. military)",
    cvxCode: 53,
    manufacturerName: "",
    mvxCode: "",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "9-Aug-13",
  },
  {
    name: "VAQTA-ADULT",
    shortDescription: "Hep A, adult",
    cvxCode: 52,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "VAQTA-PEDS",
    shortDescription: "Hep A, ped/adol, 2 dose",
    cvxCode: 83,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "9-Aug-13",
  },
  {
    name: "VARIVAX",
    shortDescription: "varicella",
    cvxCode: 21,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "VAXCHORA",
    shortDescription: "cholera, live attenuated",
    cvxCode: 174,
    manufacturerName: "Emergent Travel Health, Inc (Formerly PaxVax)",
    mvxCode: "PAX",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "17-Jun-16",
  },
  {
    name: "VAXELIS",
    shortDescription: "DTaP,IPV,Hib,HepB",
    cvxCode: 146,
    manufacturerName:
      "MSP Vaccine Company - (partnership Merck and Sanofi Pasteur)",
    mvxCode: "MSP",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "21-Jul-21",
  },
  {
    name: "VAXNEUVANCE",
    shortDescription:
      "Pneumococcal conjugate PCV15, polysaccharide CRM197 conjugate, adjuvant, PF",
    cvxCode: 215,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "18-Aug-21",
  },
  {
    name: "Vivotif",
    shortDescription: "typhoid, oral",
    cvxCode: 25,
    manufacturerName: "Emergent Travel Health, Inc (Formerly PaxVax)",
    mvxCode: "PAX",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "23-Jul-21",
  },
  {
    name: "VIVOTIF BERNA",
    shortDescription: "typhoid, oral",
    cvxCode: 25,
    manufacturerName: "Crucell",
    mvxCode: "CRU",
    mvxStatus: "Inactive",
    status: "Inactive",
    updateDate: "2-May-16",
  },
  {
    name: "YF-VAX",
    shortDescription: "yellow fever",
    cvxCode: 37,
    manufacturerName: "Sanofi Pasteur",
    mvxCode: "PMC",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
  {
    name: "ZOSTAVAX",
    shortDescription: "zoster live",
    cvxCode: 121,
    manufacturerName: "Merck and Co., Inc.",
    mvxCode: "MSD",
    mvxStatus: "Active",
    status: "Active",
    updateDate: "28-May-10",
  },
];

export const vaccineProductData = data?.map(({ cvxCode, mvxCode, name, status, updateDate }) => ({ cvxCode: cvxCode?.toString(), mvxCode, name, status, updateDate}))