import {MigrationInterface, QueryRunner} from "typeorm";

export class changedServiceCodesEnum1657100475918 implements MigrationInterface {
    name = 'changedServiceCodesEnum1657100475918'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TYPE "public"."Contacts_servicecode_enum" RENAME TO "Contacts_servicecode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."Contacts_servicecode_enum" AS ENUM('01 - Pharmacy', '02 - Telehealth', '02 - Telehealth Provided Other than in Patient''s Home', '03 - School', '04 - Homeless Shelter', '05 - Indian Health Service Free-standing Facility', '06 - Indian Health Service Provider-based Facility', '07 - Tribal 638 Free-standing Facility', '08 - Tribal 638 Provider-based Facility', '09 - Prison/Correctional Facility', '10 - Prison/Correctional Facility', '10 - Telehealth Provided in Patient''s Home', '11 - Office', '12 - Home', '13 - Assisted Living', '14 - Group Home', '15 - Mobile Unit', '16 - Temporary Lodging', '17 - Walk-in Retail Health Clinic', '18 - Place of Employment', '19 - Off Campus-Outpatient Hospital', '20 - Urgent Care', '21 - Inpatient Hospital', '22 - Outpatient Hospital', '23 - Emergency Room - Hospital', '24 - Ambulatory Surgical Center', '25 - Birthing Center', '26 - Military Treatment Facility', '31 - Skilled Nursing Facility', '32 - Nursing Facility', '33 - Custodial Care Facility', '34 - Hospice', '41 - Ambulance - Land', '42 - Ambulance - Air or Water', '49 - Independent Clinic', '50 - Federally Qualified Health Center', '51 - Inpatient Psychiatric Facility', '52 - Psychiatric Facility Partial Hospitilzation', '53 - Community Mental Health Center', '54 - Intermediate Care Facility/Mentally Retarded', '55 - Residential Substance Abuse Treatment Facility', '56 - Psychiatric Residential Treatment Center', '57 - Non-residential Substance Abuse Treatment Facility', '58 - Non-residential Opioid Treatment Facility', '60 - Mass Immunization Center', '61 - Comprehensive Inpatient Rehabilitation Facility', '62 - Comprehensive Outpatient Rehabilitation Facility', '65 - End Stage Renal Disease Treatment Facility', '71 - State or Local Public Health Clinic', '72 - Rural Health Clinic', '81 - Independent Laboratory', '99 - Other Unlisted Facility')`);
        await queryRunner.query(`ALTER TABLE "Contacts" ALTER COLUMN "serviceCode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Contacts" ALTER COLUMN "serviceCode" TYPE "public"."Contacts_servicecode_enum" USING "serviceCode"::"text"::"public"."Contacts_servicecode_enum"`);
        await queryRunner.query(`ALTER TABLE "Contacts" ALTER COLUMN "serviceCode" SET DEFAULT '24 - Ambulatory Surgical Center'`);
        await queryRunner.query(`DROP TYPE "public"."Contacts_servicecode_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."Facilities_servicecode_enum" RENAME TO "Facilities_servicecode_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."Facilities_servicecode_enum" AS ENUM('01 - Pharmacy', '02 - Telehealth', '02 - Telehealth Provided Other than in Patient''s Home', '03 - School', '04 - Homeless Shelter', '05 - Indian Health Service Free-standing Facility', '06 - Indian Health Service Provider-based Facility', '07 - Tribal 638 Free-standing Facility', '08 - Tribal 638 Provider-based Facility', '09 - Prison/Correctional Facility', '10 - Prison/Correctional Facility', '10 - Telehealth Provided in Patient''s Home', '11 - Office', '12 - Home', '13 - Assisted Living', '14 - Group Home', '15 - Mobile Unit', '16 - Temporary Lodging', '17 - Walk-in Retail Health Clinic', '18 - Place of Employment', '19 - Off Campus-Outpatient Hospital', '20 - Urgent Care', '21 - Inpatient Hospital', '22 - Outpatient Hospital', '23 - Emergency Room - Hospital', '24 - Ambulatory Surgical Center', '25 - Birthing Center', '26 - Military Treatment Facility', '31 - Skilled Nursing Facility', '32 - Nursing Facility', '33 - Custodial Care Facility', '34 - Hospice', '41 - Ambulance - Land', '42 - Ambulance - Air or Water', '49 - Independent Clinic', '50 - Federally Qualified Health Center', '51 - Inpatient Psychiatric Facility', '52 - Psychiatric Facility Partial Hospitilzation', '53 - Community Mental Health Center', '54 - Intermediate Care Facility/Mentally Retarded', '55 - Residential Substance Abuse Treatment Facility', '56 - Psychiatric Residential Treatment Center', '57 - Non-residential Substance Abuse Treatment Facility', '58 - Non-residential Opioid Treatment Facility', '60 - Mass Immunization Center', '61 - Comprehensive Inpatient Rehabilitation Facility', '62 - Comprehensive Outpatient Rehabilitation Facility', '65 - End Stage Renal Disease Treatment Facility', '71 - State or Local Public Health Clinic', '72 - Rural Health Clinic', '81 - Independent Laboratory', '99 - Other Unlisted Facility')`);
        await queryRunner.query(`ALTER TABLE "Facilities" ALTER COLUMN "serviceCode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Facilities" ALTER COLUMN "serviceCode" TYPE "public"."Facilities_servicecode_enum" USING "serviceCode"::"text"::"public"."Facilities_servicecode_enum"`);
        await queryRunner.query(`ALTER TABLE "Facilities" ALTER COLUMN "serviceCode" SET DEFAULT '01 - Pharmacy'`);
        await queryRunner.query(`DROP TYPE "public"."Facilities_servicecode_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."Facilities_servicecode_enum_old" AS ENUM(' Prison/Correctional Facility [09]', ' Skilled Nursing Facility [31]', ' Tribal 638 Provider-based Facility [08]', '18-Place of Employment', 'AMBULANCE - AIR OR WATER [42]', 'AMBULANCE - LAND [41]', 'AMBULATORY SURGICAL CENTER [24]', 'ASSISTED LIVING [13]', 'Ambulance - Land [41]', 'Ambulatory Surgical Center [24]', 'BIRTHING CENTER [25]', 'COMMUNITY MENTAL HEALTH CENTER [53]', 'COMPREHENSIVE INPATIENT REHABILITATION FACILITY [61]', 'COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY [62]', 'CUSTODIAL CARE FACILITY [33]', 'EMERGENCY ROOM [23]', 'END STAGE RENAL DISEASE TREATMENT FACILITY [65]', 'Emergency Room - Hospital [23]', 'FEDERALLY QUALIFIED HEALTH CENTER [50]', 'GROUP HOME [14]', 'HOMELESS SHELTER [04]', 'HOSPICE [34]', 'Home [12]', 'INDEPENDENT CLINIC [49]', 'INDEPENDENT LABORATORY [81]', 'INDIAN HEALTH SERVICE FREE-STANDING FACILITY [05]', 'INDIAN HEALTH SERVICE PROVIDER-BASED FACILITY [06]', 'Inpatient Hospital [21]', 'Inpatient Psychiatric Facility [51]', 'Intermediate Care Facility/Mentally Retarded [54]', 'Mass Immunization Center [60]', 'Military Treatment Facility [26]', 'Mobile Unit [15]', 'Non-residential Opioid Treatment Facility [58]', 'Non-residential Substance Abuse Treatment Facility [57]', 'Nursing Facility [32]', 'Off Campus-Outpatient Hospital [19]', 'Office [11]', 'Outpatient Hospital [22]', 'Pharmacy [01]', 'Prison/Correctional Facility [10]', 'Psychiatric Facility Partial Hospitilzation [52]', 'Psychiatric Residential Treatment Center [56]', 'Residential Substance Abuse Treatment Facility [55]', 'Rural Health Clinic- [72]', 'School [03]', 'State or Local Public Health Clinic [71]', 'Telehealth Provided Other than in Patient''s Home [02]', 'Telehealth Provided in Patient''s Home [10]', 'Telehealth [02]', 'Temporary Lodging [16]', 'Tribal 638 Free-standing Facility [07]', 'Urgent Care [20]', 'Walk-in Retail Health Clinic [17]')`);
        await queryRunner.query(`ALTER TABLE "Facilities" ALTER COLUMN "serviceCode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Facilities" ALTER COLUMN "serviceCode" TYPE "public"."Facilities_servicecode_enum_old" USING "serviceCode"::"text"::"public"."Facilities_servicecode_enum_old"`);
        await queryRunner.query(`ALTER TABLE "Facilities" ALTER COLUMN "serviceCode" SET DEFAULT 'AMBULATORY SURGICAL CENTER [24]'`);
        await queryRunner.query(`DROP TYPE "public"."Facilities_servicecode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."Facilities_servicecode_enum_old" RENAME TO "Facilities_servicecode_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."Contacts_servicecode_enum_old" AS ENUM('AMBULANCE - AIR OR WATER [42]', 'AMBULANCE - LAND [41]', 'AMBULATORY SURGICAL CENTER [24]', 'ASSISTED LIVING [13]', 'BIRTHING CENTER [25]', 'COMMUNITY MENTAL HEALTH CENTER [53]', 'COMPREHENSIVE INPATIENT REHABILITATION FACILITY [61]', 'COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY [62]', 'CUSTODIAL CARE FACILITY [33]', 'EMERGENCY ROOM [23]', 'END STAGE RENAL DISEASE TREATMENT FACILITY [65]', 'FEDERALLY QUALIFIED HEALTH CENTER [50]', 'GROUP HOME [14]', 'HOMELESS SHELTER [04]', 'HOSPICE [34]', 'INDEPENDENT CLINIC [49]', 'INDEPENDENT LABORATORY [81]', 'INDIAN HEALTH SERVICE FREE-STANDING FACILITY [05]', 'INDIAN HEALTH SERVICE PROVIDER-BASED FACILITY [06]')`);
        await queryRunner.query(`ALTER TABLE "Contacts" ALTER COLUMN "serviceCode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Contacts" ALTER COLUMN "serviceCode" TYPE "public"."Contacts_servicecode_enum_old" USING "serviceCode"::"text"::"public"."Contacts_servicecode_enum_old"`);
        await queryRunner.query(`ALTER TABLE "Contacts" ALTER COLUMN "serviceCode" SET DEFAULT 'AMBULATORY SURGICAL CENTER [24]'`);
        await queryRunner.query(`DROP TYPE "public"."Contacts_servicecode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."Contacts_servicecode_enum_old" RENAME TO "Contacts_servicecode_enum"`);
    }

}
