import { ElementType } from '../entities/element.entity'
import { FormType } from '../entities/form.entity'
//elements for seed
export const ElementTypeData = [
	{ type: ElementType.CHECKBOX },
	{ type: ElementType.DATE },
	{ type: ElementType.FILE },
	{ type: ElementType.EMAIL },
	{ type: ElementType.NUMBER },
	{ type: ElementType.RADIO },
	{ type: ElementType.SELECT },
	{ type: ElementType.TEXT },
]


//Form template
export const FormTemplates = [
	{
		layout: {
			sections: [
				{
					id: "8ada68b2-cd15-4370-af7c-2121e920ad63",
					col: 12,
					name: "Section",
					fields: [
						{
							css: "",
							name: "location",
							type: ElementType.SELECT,
							label: "Location",
							column: 6,
							fieldId: "db48cd38-115f-4c5a-ba99-0cb04d57dbde",
							options: [
								{
									name: "Medial",
									value: "medial",
								},
								{
									name: "Lateral",
									value: "lateral",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select Locations",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "location_comments",
							type: ElementType.TEXT,
							label: "Location Comments",
							column: 6,
							fieldId: "a35ef1eb-e538-48fb-b4e0-0cc78a9c219b",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter location comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "quality",
							type: ElementType.SELECT,
							label: "Quality",
							column: 6,
							fieldId: "25f4cfab-1338-4eab-958c-9f46b183d6e0",
							options: [
								{
									name: "Not Known",
									value: "not_known",
								},
								{
									name: "Aching",
									value: " aching",
								},
								{
									name: "Acute",
									value: "acute",
								},
								{
									name: "Burning",
									value: "burning",
								},
								{
									name: "Chronic",
									value: "chronic",
								},
								{
									name: "Constant",
									value: "constant",
								},
								{
									name: "Cramping",
									value: "cramping",
								},
								{
									name: "Crushing",
									value: "crushing",
								},
								{
									name: "Dull",
									value: "dull",
								},
								{
									name: "Electrical",
									value: "electrical",
								},
								{
									name: "Radiating Pain",
									value: "radiating_pain",
								},
								{
									name: "Sharp",
									value: "sharp",
								},
								{
									name: "Stabbing",
									value: "stabbing",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select qualities",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "quality_comments",
							type: ElementType.TEXT,
							label: "Quality Comments",
							column: 6,
							fieldId: "f62b2eec-72b1-44cc-bdea-2b01cdd1b931",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Quality Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "severity",
							type: ElementType.SELECT,
							label: "Severity",
							column: 6,
							fieldId: "a348f448-849b-4a20-9082-afbdc5ac6289",
							options: [
								{
									name: "1 out of 10",
									value: "1_out_of_10",
								},
								{
									name: "2 out of 10",
									value: "2_out_of_10",
								},
								{
									name: "3 out of 10",
									value: "3_out_of_10",
								},
								{
									name: "4 out of 10",
									value: "4_out_of_10",
								},
								{
									name: "5 out of 10",
									value: "5_out_of_10",
								},
								{
									name: "6 out of 10",
									value: "6_out_of_10",
								},
								{
									name: "7 out of 10",
									value: "7_out_of_10",
								},
								{
									name: "8 out of 10",
									value: "8_out_of_10",
								},
								{
									name: "9 out of 10",
									value: "9_out_of_10",
								},
								{
									name: "10 out of 10",
									value: "10_out_of_10",
								},
								{
									name: "Acute Distress",
									value: "acute_distress",
								},
								{
									name: "Critical",
									value: "critical",
								},
								{
									name: "LOC",
									value: "loc",
								},
								{
									name: "Mild",
									value: "mild",
								},
								{
									name: "Mild to Moderate",
									value: "mild_to_moderate",
								},
								{
									name: "Moderate",
									value: "moderate",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select Severity",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "severity_comments",
							type: ElementType.TEXT,
							label: "Severity Comments",
							column: 6,
							fieldId: "5da4c584-a5a4-4bc2-a2d9-f2de2b0ad9d6",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Severity Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "duration",
							type: ElementType.SELECT,
							label: "Duration",
							column: 6,
							fieldId: "519b1360-9b60-4ee7-a33d-edaa262a8e57",
							options: [
								{
									name: "Getting Better",
									value: "getting_better",
								},
								{
									name: "Steady",
									value: "steady",
								},
								{
									name: " Have been increasing since onset",
									value: "have_been_increasing_since_onset",
								},
								{
									name: " % of time symptoms are experienced as in SOAP",
									value: " % of time symptoms are experienced as in SOAP",
								},
								{
									name: " has had same/similar condition in the past",
									value: " has had same/similar condition in the past",
								},
								{
									name: " Most symptomatic in morning",
									value: " most symptomatic in morning",
								},
								{
									name: "Most symptomatic in mid day",
									value: "most symptomatic in mid day",
								},
								{
									name: "Most symptomatic in evening",
									value: "most symptomatic in evening",
								},
								{
									name: "Wakes up from sleep",
									value: "wakes up from sleep",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select duration",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "duration_comments",
							type: ElementType.TEXT,
							label: "Duration Comments",
							column: 6,
							fieldId: "eea8fa7d-ac3a-4dbf-9f65-c8f5d651ef96",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Duration Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "onset_or_timing",
							type: ElementType.SELECT,
							label: "Onset / Timing",
							column: 6,
							fieldId: "12471e12-d669-40ec-ac82-e1c705a5a477",
							options: [
								{
									name: "Abrupt",
									value: "abrupt",
								},
								{
									name: "After Meal",
									value: "after_meal",
								},
								{
									name: "At Rest",
									value: "at_rest",
								},
								{
									name: "Awakened from Sleep",
									value: "awakened_from_sleep",
								},
								{
									name: "Continuous",
									value: "continuous",
								},
								{
									name: "Date of Occurrence",
									value: "date_of_occurrence",
								},
								{
									name: "Episodes",
									value: "episodes",
								},
								{
									name: "Gradual",
									value: "gradual",
								},
								{
									name: "Intermittent",
									value: "intermittent",
								},
								{
									name: "Primarily Nocturnal",
									value: "primarily_nocturnal",
								},
								{
									name: "Time not known",
									value: "time_not_known",
								},
								{
									name: "1 Day Ago",
									value: "1_day_ago",
								},
								{
									name: "Days Ago",
									value: "days_ago",
								},
								{
									name: "1 Week Ago",
									value: "1_week_ago",
								},
								{
									name: "Weeks ago",
									value: "weeks_ago",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please Select Onset / Timing",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "onset_comments",
							type: ElementType.TEXT,
							label: "Onset Comments",
							column: 6,
							fieldId: "a4d1fc71-36a1-4968-947a-ac8a9af75279",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Onset Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "context",
							type: ElementType.SELECT,
							label: "Context",
							column: 6,
							fieldId: "0739cdcc-0ac2-4a4e-bc33-5d45e72757e8",
							options: [
								{
									name: "At rest",
									value: "at_rest",
								},
								{
									name: "During physical exertion",
									value: "during_physical_exertion",
								},
								{
									name: "During mental exertion",
									value: "during_mental_exertion",
								},
								{
									name: "During a sporting activity",
									value: "during_a_sporting_activity",
								},
								{
									name: "At work",
									value: "at_work",
								},
								{
									name: "With familial stress",
									value: "with_familial_stress",
								},
								{
									name: "Mechanism issues",
									value: "mechanism_issues",
								},
								{
									name: "Post hospital visit",
									value: "post_hospital_visit",
								},
								{
									name: "Pre hospital visit",
									value: "pre_hospital_visit",
								},
								{
									name: "Gegan after discharge from hospital",
									value: "began_after_discharge_from_hospital",
								},
								{
									name: "He/She was recently treated by doctor",
									value: "he/she_was_recently_treated_by_doctor",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please  select Contexts",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "context_comments",
							type: ElementType.TEXT,
							label: "Context Comments",
							column: 6,
							fieldId: "411f4623-707e-4f1f-9fa9-ab6af2d977fa",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Context Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "modifying_factors",
							type: ElementType.SELECT,
							label: "Modifying Factors",
							column: 6,
							fieldId: "5eef142c-59ab-41b3-a83a-aac9e3559383",
							options: [
								{
									name: "Abated on their own",
									value: "abated_on_their_own",
								},
								{
									name: "Abated when on medication(s)",
									value: "abated_when_on_medication(s)",
								},
								{
									name: "Increased with inspiration",
									value: "increased_with_inspiration",
								},
								{
									name: "Exacerbate with movement",
									value: "exacerbate_with_movement",
								},
								{
									name: "Decrease with movement",
									value: " decrease_with_movement",
								},
								{
									name: "Have partially resolved seemingly on their own",
									value: "have_partially_resolved_seemingly_on_their_own",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select Modifying Factors",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "modifying_factors_comments",
							type: ElementType.TEXT,
							label: "Modifying Factors Comments",
							column: 6,
							fieldId: "360f47a0-4325-46f6-914c-7c6cbf7c1343",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Modifying Factors Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "associated_symptoms",
							type: ElementType.SELECT,
							label: "Associated Symptoms",
							column: 6,
							fieldId: "85f81e33-7b80-4039-906a-0da432015277",
							options: [
								{
									name: "Numbness",
									value: "numbness",
								},
								{
									name: "Tingling",
									value: "tingling",
								},
								{
									name: "Weakness",
									value: "weakness",
								},
								{
									name: "Headache",
									value: "headache",
								},
								{
									name: "Change in vision",
									value: "change_in_vision",
								},
								{
									name: "Dizziness",
									value: "dizziness",
								},
								{
									name: "Loss of bowel control",
									value: "loss_of_bowel_control",
								},
								{
									name: "Loss of bladder control",
									value: "loss_of_bladder_control",
								},
								{
									name: "Sexual dysfunction",
									value: "sexual_dysfunction",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please Select Associated Symptoms",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "associated_symptoms_comments",
							type: ElementType.TEXT,
							label: "Associated Symptoms Comments",
							column: 6,
							fieldId: "c8254f45-963c-48fb-9b53-820b232aa23e",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Associated Symptoms Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "944d6a43-372d-46d4-9b73-430928930df0",
							type: ElementType.TEXT,
							label: "Previous Treatment",
							column: 12,
							fieldId: "e2b7d217-9816-4e52-9279-89a3db61ea81",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Previous Treatment",
							defaultValue: "",
							isMultiSelect: false,
						},
					],
				},
			],
		},
		name: "H&P CC / History of Present Illness",
		type: FormType.TEMPLATE,
		isSystemForm: true,
		isActive: true
	}, {
		layout: {
			sections: [
				{
					id: "89013df0-d818-47c8-bef4-7df14b8af24a",
					col: 12,
					name: "SOAP Plan",
					fields: [
						{
							css: "",
							name: "labs",
							type: ElementType.SELECT,
							label: "Labs",
							column: 6,
							fieldId: "88a82fac-d80b-4950-b1f2-29137c7596f5",
							options: [
								{
									name: "LABS (to be done at Quest)",
									value: "LABS (to be done at Quest)",
								},
								{
									name: "LABS (to be done at LabCorp)",
									value: "LABS (to be done at LabCorp)",
								},
								{
									name: "LABS (to be done at Athena)",
									value: "LABS (to be done at Athena)",
								},
								{
									name: "Electrolyte panel",
									value: "Electrolyte panel",
								},
								{
									name: "Hepatic function panel",
									value: "Hepatic function panel",
								},
								{
									name: "Basic metabolic panel",
									value: "Basic metabolic panel",
								},
								{
									name: "Carbamazepine level",
									value: "Carbamazepine level",
								},
								{
									name: "Comp metabolic panel",
									value: "Comp metabolic panel",
								},
								{
									name: "Lipid panel",
									value: "Lipid panel",
								},
								{
									name: "Hepatitis panel",
									value: "Hepatitis panel",
								},
								{
									name: "Hypercoagulation Panel: Protein C; Protein S; Cardiolipin Ab; Russel viper venom; Antithrombin III; APCR; ANA; Sed rate",
									value:
										"Hypercoagulation Panel: Protein C; Protein S; Cardiolipin Ab; Russel viper venom; Antithrombin III; APCR; ANA; Sed rate",
								},
								{
									name: "Homocysteine",
									value: "Homocysteine",
								},
								{
									name: "Autoimmune Panel: ANA; Anti SSA/SSB; Actin Ab IgG; Scleroderma Ab; Anti Jo-1 Ab; Anti DNA-DS; Anti RNP",
									value:
										"Autoimmune Panel: ANA; Anti SSA/SSB; Actin Ab IgG; Scleroderma Ab; Anti Jo-1 Ab; Anti DNA-DS; Anti RNP",
								},
								{
									name: "Immunologic Indicated Panel: ANA; Rheum Arth factor; Complement C3; Immunofixation; IgA; IgM; IgG",
									value:
										"Immunologic Indicated Panel: ANA; Rheum Arth factor; Complement C3; Immunofixation; IgA; IgM; IgG",
								},
								{
									name: "Infectious Disease Panel: HIV 1 Ab; HTLV I/II Ab; Lyme disease Ab; Hep B SAb; Hep C Ab",
									value:
										"Infectious Disease Panel: HIV 1 Ab; HTLV I/II Ab; Lyme disease Ab; Hep B SAb; Hep C Ab",
								},
								{
									name: "Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
									value:
										"Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
								},
								{
									name: "Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
									value:
										"Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
								},
								{
									name: "Infectious Neuropathies Panel: Cytomegalovirus; Herpes simplex virus IgG / IgM; Herpes zoster (shingles); Hep C Ab; Hep B 006510; HIV Ab; Lyme dis IgG/IgM Ab screen; Corynebacterium diphtheria culture; Mycobacterium leprae culture; Chagas dis",
									value:
										"Infectious Neuropathies Panel: Cytomegalovirus; Herpes simplex virus IgG / IgM; Herpes zoster (shingles); Hep C Ab; Hep B 006510; HIV Ab; Lyme dis IgG/IgM Ab screen; Corynebacterium diphtheria culture; Mycobacterium leprae culture; Chagas dis",
								},
								{
									name: "Neuropathic Toxins Panel: Acrylamide; Arsenic; Lead; Mercury; Organophosphates; Platinum",
									value:
										"Neuropathic Toxins Panel: Acrylamide; Arsenic; Lead; Mercury; Organophosphates; Platinum",
								},
								{
									name: "ANA",
									value: "ANA",
								},
								{
									name: "ANCA",
									value: "ANCA",
								},
								{
									name: "Anti DNA-DS",
									value: "Anti DNA-DS",
								},
								{
									name: "Anti Parietal Cell Ab",
									value: "Anti Parietal Cell Ab",
								},
								{
									name: "Anti Cardiolipin Ab",
									value: "Anti Cardiolipin Ab",
								},
								{
									name: "Anti Hu",
									value: "Anti Hu",
								},
								{
									name: "Anti Thrombin III",
									value: "Anti Thrombin III",
								},
								{
									name: "Anti Yo",
									value: "Anti Yo",
								},
								{
									name: "Campylobact. jejuni titer",
									value: "Campylobact. jejuni titer",
								},
								{
									name: "Complement C3 C4",
									value: "Complement C3 C4",
								},
								{
									name: "Complement CH50",
									value: "Complement CH50",
								},
								{
									name: "CBC with diff",
									value: "CBC with diff",
								},
								{
									name: "Ceruloplasmin",
									value: "Ceruloplasmin",
								},
								{
									name: "Serum copper",
									value: "Serum copper",
								},
								{
									name: "CPK",
									value: "CPK",
								},
								{
									name: "CRP",
									value: "CRP",
								},
								{
									name: "Cryoglobulin",
									value: "Cryoglobulin",
								},
								{
									name: "Factor V Leiden",
									value: "Factor V Leiden",
								},
								{
									name: "Folate",
									value: "Folate",
								},
								{
									name: "Glucose fasting",
									value: "Glucose fasting",
								},
								{
									name: "Glucose tolerance test 2hr",
									value: "Glucose tolerance test 2hr",
								},
								{
									name: "Glucose tolerance test 3hr",
									value: "Glucose tolerance test 3hr",
								},
								{
									name: "HgBA1C",
									value: "HgBA1C",
								},
								{
									name: "HIV-1/2 SCR w/RFX WB confirm",
									value: "HIV-1/2 SCR w/RFX WB confirm",
								},
								{
									name: "HIV-1 RNA PCR quantitative",
									value: "HIV-1 RNA PCR quantitative",
								},
								{
									name: "Homocysteine",
									value: "Homocysteine",
								},
								{
									name: "Immunofixation serum",
									value: "Immunofixation serum",
								},
								{
									name: "Intrinsic factor Ab",
									value: "Intrinsic factor Ab",
								},
								{
									name: "Iron (tot) IBC % sat",
									value: "Iron (tot) IBC % sat",
								},
								{
									name: "Iron total",
									value: "Iron total",
								},
								{
									name: "Lambert-Eaton syndrome Ab",
									value: "Lambert-Eaton syndrome Ab",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please select Labs",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "lab_comments",
							type: ElementType.TEXT,
							label: "Lab Comments",
							column: 6,
							fieldId: "ddb454f6-d11b-4118-ada6-624c2a739465",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter lab comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "radiology",
							type: ElementType.SELECT,
							label: "Radiology",
							column: 6,
							fieldId: "bd20bb02-3ab3-4952-9de1-c62a5e9a47f9",
							options: [
								{
									name: "Open MRI",
									value: "Open MRI",
								},
								{
									name: "Upright MRI",
									value: "Upright MRI",
								},
								{
									name: "MRI brain with and without contrast",
									value: "MRI brain with and without contrast",
								},
								{
									name: "MRI brain without contrast",
									value: "MRI brain without contrast",
								},
								{
									name: "MRI brain 3.0 T with and without contrast",
									value: "MRI brain 3.0 T with and without contrast",
								},
								{
									name: "MRI brain 3.0 T without contrast",
									value: "MRI brain 3.0 T without contrast",
								},
								{
									name: "MRA brain with and without contrast",
									value: "MRA brain with and without contrast",
								},
								{
									name: "MRA brain without contrast",
									value: "MRA brain without contrast",
								},
								{
									name: "CT scan brain with and without contrast",
									value: "CT scan brain with and without contrast",
								},
								{
									name: "CT scan brain without contrast",
									value: "CT scan brain without contrast",
								},
								{
									name: "CTA head and neck",
									value: "CTA head and neck",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter radiology",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "radiology_comments",
							type: ElementType.TEXT,
							label: "Radiology Comments",
							column: 6,
							fieldId: "1125b9c7-c8f2-4156-b395-518cdc8b5aac",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter Radiology Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "PT Recommendations",
							type: ElementType.SELECT,
							label: "PT Recommendations",
							column: 6,
							fieldId: "d4936f49-8e28-4c0b-885a-b6eedf49ff05",
							options: [
								{
									name: "Evaluate and Teat",
									value: "Evaluate and Teat",
								},
								{
									name: "Exercise",
									value: "Exercise",
								},
								{
									name: "Manual Therapy",
									value: "Manual Therapy",
								},
								{
									name: "Chronic Pain Program",
									value: "Chronic Pain Program",
								},
								{
									name: "Posture/Position/Body Mechanics",
									value: "Posture/Position/Body Mechanics",
								},
								{
									name: "AROM",
									value: "AROM",
								},
								{
									name: "PROM",
									value: "PROM",
								},
								{
									name: "Back school",
									value: "Back school",
								},
								{
									name: "Gait training",
									value: "Gait training",
								},
								{
									name: "McKenzie Program",
									value: "McKenzie Program",
								},
								{
									name: "Aquatic Therapy",
									value: "Aquatic Therapy",
								},
								{
									name: "Neuro Re-education",
									value: "Neuro Re-education",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter PT Recommendations",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "PT Recommendation Comments",
							type: ElementType.TEXT,
							label: "PT Recommendation Comments",
							column: 6,
							fieldId: "2db82468-9665-4f6a-b49c-565c474c2bc1",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter PT Recommendation Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "Home Health ",
							type: ElementType.SELECT,
							label: "Home Health ",
							column: 6,
							fieldId: "b0d78594-feea-4250-84db-ff844cacd782",
							options: [
								{
									name: "Skilled Nursing:",
									value: "Skilled Nursing:",
								},
								{
									name: "Eval & Instruct for:",
									value: "Eval & Instruct for:",
								},
								{
									name: "Medication",
									value: "Medication",
								},
								{
									name: "Pain",
									value: "Pain",
								},
								{
									name: "Cardiac",
									value: "Cardiac",
								},
								{
									name: "Diabetic Management",
									value: "Diabetic Management",
								},
								{
									name: "Respiratory",
									value: "Respiratory",
								},
								{
									name: "Physical Therapy:",
									value: "Physical Therapy:",
								},
								{
									name: "Weakness",
									value: "Weakness",
								},
								{
									name: "Ambulation/Gait",
									value: "Ambulation/Gait",
								},
								{
									name: "Balance",
									value: "Balance",
								},
								{
									name: "Transfers",
									value: "Transfers",
								},
								{
									name: "Bed Mobility",
									value: "Bed Mobility",
								},
								{
									name: "Fall Risk",
									value: "Fall Risk",
								},
								{
									name: "Range of Motion",
									value: "Range of Motion",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter Home Health ",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "Home health comments",
							type: ElementType.TEXT,
							label: "Home health comments",
							column: 6,
							fieldId: "9a06c5e8-32b6-4bfb-98bf-2fbb5afe1726",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter Home health comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "Referrals ",
							type: ElementType.TEXT,
							label: "Referrals ",
							column: 6,
							fieldId: "8e78871f-3c18-49c4-b026-101bce43c440",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter Referrals ",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "Referral Comments",
							type: ElementType.TEXT,
							label: "Referral Comments",
							column: 6,
							fieldId: "6733821f-d67b-415f-8f7a-b1b6dc94b091",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter Referral Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "Education",
							type: ElementType.SELECT,
							label: "Education",
							column: 6,
							fieldId: "06074222-d112-429e-96ac-440ea0bfad54",
							options: [
								{
									name: "Alternative treatments",
									value: "Alternative treatments",
								},
								{
									name: "Drug interactions",
									value: "Alternative Drug interactions",
								},
								{
									name: "Handouts provided",
									value: "Handouts provided",
								},
								{
									name: "Medication side effects",
									value: "Medication side effects",
								},
								{
									name: "Pain management",
									value: "Pain management",
								},
								{
									name: "Potential adverse consequences if pregnant",
									value: "Potential adverse consequences if pregnant",
								},
								{
									name: "Recognizing stroke-like symptoms",
									value: "Recognizing stroke-like symptoms",
								},
								{
									name: "Risks of declining treatment",
									value: "Risks of declining treatment",
								},
								{
									name: "Risks/benefits of treatment plan",
									value: "Risks/benefits of treatment plan",
								},
								{
									name: "Signs of emergency",
									value: "Signs of emergency",
								},
								{
									name: "Symptom management",
									value: "Symptom management",
								},
								{
									name: "Written instructions for tapering/titrating medications",
									value: "Written instructions for tapering/titrating medications",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please select Education",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "Education Comments",
							type: ElementType.TEXT,
							label: "Education Comments",
							column: 6,
							fieldId: "3f36d1d3-ba39-4db6-90ed-060143e48f5a",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please enter Education Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "Diet",
							type: ElementType.SELECT,
							label: "Diet",
							column: 6,
							fieldId: "a22ddd61-3984-4de8-93c6-cbbda6c07b59",
							options: [
								{
									name: "1800 cal ADA diet",
									value: "1800 cal ADA diet",
								},
								{
									name: "1800 cal ADA diet",
									value: "1800 cal ADA diet",
								},
								{
									name: "2000 cal ADA diet",
									value: "2000 cal ADA diet",
								},
								{
									name: "1500 cal ADA diet",
									value: "1500 cal ADA diet",
								},
								{
									name: "Low fat diet",
									value: "Low fat diet",
								},
								{
									name: "Low sodium diet",
									value: "Low sodium diet",
								},
								{
									name: "Low cholesterol diet",
									value: "Low cholesterol diet",
								},
								{
									name: "Adequate nutritional intake",
									value: "Adequate nutritional intake",
								},
								{
									name: "Vitamin supplementation",
									value: "Vitamin supplementation",
								},
								{
									name: "Avoid alcohol",
									value: "Avoid alcohol",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please select a Diet",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "Diet Comments",
							type: ElementType.TEXT,
							label: "Diet Comments",
							column: 6,
							fieldId: "83fafb10-287d-4465-b15a-a0be1d0115dc",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please leave Diet Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "General Instructions ",
							type: ElementType.SELECT,
							label: "General Instructions ",
							column: 6,
							fieldId: "86a81979-37ed-4dc3-b48e-5bcbd4a15e29",
							options: [
								{
									name: "Activity as tolerated",
									value: "Activity as tolerated",
								},
								{
									name: "Activity as tolerated",
									value: "Activity as tolerated",
								},
								{
									name: "Avoid crowds",
									value: "Avoid crowds",
								},
								{
									name: "Avoid driving",
									value: "Avoid driving",
								},
								{
									name: "Avoid high risk activity due to seizures/LOC",
									value: "Avoid high risk activity due to seizures/LOC",
								},
								{
									name: "Follow exercise program",
									value: "Follow exercise program",
								},
								{
									name: "Follow facial exercise program",
									value: "Follow facial exercise program",
								},
								{
									name: "Increase activity level",
									value: "Increase activity level",
								},
								{
									name: "No heavy lifting",
									value: "No heavy lifting",
								},
								{
									name: "No heavy lifting more than 5 lbs",
									value: "No heavy lifting more than 5 lbs",
								},
								{
									name: "No heavy lifting more than 10 lbs",
									value: "No heavy lifting more than 10 lbs",
								},
								{
									name: "No heavy lifting more than 20 lbs",
									value: "No heavy lifting more than 20 lbs",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please select General Instructions ",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "General Instruction Comments",
							type: ElementType.TEXT,
							label: "General Instruction Comments",
							column: 6,
							fieldId: "c58e2a82-3903-4917-a964-0485b1b9f5ee",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							placeholder: "Please leave General Instruction Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
					],
				},
			],
		},
		name: "SOAP Plan",
		type: FormType.TEMPLATE,
		isSystemForm: true,
		isActive: true
	}
]