import { v4 as uuid } from 'uuid'

import { RelationshipType } from 'src/providers/entities/contact.entity';
import { ElementType } from "../entities/element.entity";
import { FormType } from "../entities/form.entity";
import { RACE, ETHNICITY, SEXUALORIENTATION, MARITIALSTATUS, GENDERIDENTITY, PRONOUNS, HOMEBOUND } from 'src/patients/entities/patient.entity'

//elements for seed
export const ElementTypeData = [
  { type: ElementType.CHECKBOX },
  { type: ElementType.DATE },
  { type: ElementType.FILE },
  { type: ElementType.EMAIL },
  { type: ElementType.NUMBER },
  { type: ElementType.RADIO },
  { type: ElementType.SELECT },
  { type: ElementType.TEXT },
  { type: ElementType.TEL },
];

const MAPPED_RELATIONSHIP_TYPE = [
  { value: RelationshipType.WARD, name: RelationshipType.WARD },
  { value: RelationshipType.SELF, name: RelationshipType.SELF },
  { value: RelationshipType.CHILD, name: RelationshipType.CHILD },
  { value: RelationshipType.OTHER, name: RelationshipType.OTHER },
  { value: RelationshipType.MOTHER, name: RelationshipType.MOTHER },
  { value: RelationshipType.SPOUSE, name: RelationshipType.SPOUSE },
  { value: RelationshipType.FATHER, name: RelationshipType.FATHER },
  { value: RelationshipType.UNKNOWN, name: RelationshipType.UNKNOWN },
  { value: RelationshipType.EMPLOYEE, name: RelationshipType.EMPLOYEE },
  { value: RelationshipType.ORGAN_DONOR, name: RelationshipType.ORGAN_DONOR },
  { value: RelationshipType.GRANDCHILD, name: RelationshipType.GRANDCHILD },
  { value: RelationshipType.LIFE_PARTNER, name: RelationshipType.LIFE_PARTNER },
  { value: RelationshipType.GRANDPARENT, name: RelationshipType.GRANDPARENT },
  { value: RelationshipType.NEPHEW_NIECE, name: RelationshipType.NEPHEW_NIECE },
  { value: RelationshipType.FOSTHER_CHILD, name: RelationshipType.FOSTHER_CHILD },
  { value: RelationshipType.CADAVER_DONOR, name: RelationshipType.CADAVER_DONOR },
  { value: RelationshipType.SIGNIFICANT_OTHER, name: RelationshipType.SIGNIFICANT_OTHER },
  { value: RelationshipType.EMANCIPATED_MINOR, name: RelationshipType.EMANCIPATED_MINOR },
  { value: RelationshipType.INJURED_PLAINTIIFF, name: RelationshipType.INJURED_PLAINTIIFF },
  { value: RelationshipType.SPONSORED_DEPENDENT, name: RelationshipType.SPONSORED_DEPENDENT },
  { value: RelationshipType.STEPSON_STEPDAUGHTER, name: RelationshipType.STEPSON_STEPDAUGHTER },
  { value: RelationshipType.CHILD_MOTHER_INSURANCE, name: RelationshipType.CHILD_MOTHER_INSURANCE },
  { value: RelationshipType.HANDICAPPED_DEPENDENT, name: RelationshipType.HANDICAPPED_DEPENDENT },
  { value: RelationshipType.CHILD_FATHER_INSURANCE, name: RelationshipType.CHILD_FATHER_INSURANCE },
  { value: RelationshipType.DEPENDENT_OF_MINOR_DEPENDENT, name: RelationshipType.DEPENDENT_OF_MINOR_DEPENDENT },
  { value: RelationshipType.STEPSON_STEPDAUGHTER_STEPMOTHER_INSRTANCE, name: RelationshipType.STEPSON_STEPDAUGHTER_STEPMOTHER_INSRTANCE, },
  { value: RelationshipType.STEPSON_STEPDAUGHTER_STEPFATHER_INSRTANCE, name: RelationshipType.STEPSON_STEPDAUGHTER_STEPFATHER_INSRTANCE, },
];

const MAPPED_RACE = [
  { value: RACE.OTHER, name: RACE.OTHER },
  { value: RACE.ASIAN, name: RACE.ASIAN },
  { value: RACE.WHITE, name: RACE.WHITE },
  {
    value: RACE.BLACK_AFRICAN_AMERICAN,
    name: RACE.BLACK_AFRICAN_AMERICAN,
  },
  {
    value: RACE.BLACK_AFRICAN_AMERICAN,
    name: RACE.BLACK_AFRICAN_AMERICAN,
  },
  {
    value: RACE.AMERICAN_INDIAN_ALASKA_NATIVE,
    name: RACE.AMERICAN_INDIAN_ALASKA_NATIVE,
  },
  {
    value: RACE.NATIVE_HAWAIIAN_PACIFIC_ISLANDER,
    name: RACE.NATIVE_HAWAIIAN_PACIFIC_ISLANDER,
  },
];

const MAPPED_ETHNICITY = [
  { value: ETHNICITY.NONE, name: ETHNICITY.NONE },
  { value: ETHNICITY.CENTERAL_AMERICAN, name: ETHNICITY.CENTERAL_AMERICAN, },
  { value: ETHNICITY.CENTERAL_AMERICAN_INDIAN, name: ETHNICITY.CENTERAL_AMERICAN_INDIAN, },
];

const MAPPED_SEXUAL_ORIENTATION = [
  { value: SEXUALORIENTATION.NONE, name: SEXUALORIENTATION.NONE },
  { value: SEXUALORIENTATION.DONT_KNOW, name: SEXUALORIENTATION.DONT_KNOW, },
  { value: SEXUALORIENTATION.BISEXUAL, name: SEXUALORIENTATION.BISEXUAL, },
  { value: SEXUALORIENTATION.HOMOSEXUAL, name: SEXUALORIENTATION.HOMOSEXUAL, },
  { value: SEXUALORIENTATION.HETEROSEXUAL, name: SEXUALORIENTATION.HETEROSEXUAL, },
];

const MAPPED_HOMEBOUND = [
  { value: HOMEBOUND.NO, name: HOMEBOUND.NO },
  { value: HOMEBOUND.YES, name: HOMEBOUND.YES },
];

const MAPPED_GENDER_IDENTITY = [
  { value: GENDERIDENTITY.NONE, name: GENDERIDENTITY.NONE },
  { value: GENDERIDENTITY.MALE, name: GENDERIDENTITY.MALE },
  { value: GENDERIDENTITY.FEMALE, name: GENDERIDENTITY.FEMALE },
  { value: GENDERIDENTITY.NOT_EXCLUSIVE, name: GENDERIDENTITY.NOT_EXCLUSIVE, },
];

const MAPPED_MARITAL_STATUS = [
  { value: MARITIALSTATUS.SINGLE, name: MARITIALSTATUS.SINGLE },
  { value: MARITIALSTATUS.WIDOWED, name: MARITIALSTATUS.WIDOWED },
  { value: MARITIALSTATUS.DIVORCED, name: MARITIALSTATUS.DIVORCED },
  { value: MARITIALSTATUS.SEPARATED, name: MARITIALSTATUS.SEPARATED },
];

const MAPPED_PRONOUNS = [
  { value: PRONOUNS.HE, name: PRONOUNS.HE },
  { value: PRONOUNS.SHE, name: PRONOUNS.SHE },
  { value: PRONOUNS.NONE, name: PRONOUNS.NONE },
];
//Form template
export const FormTemplates = [
  {
    layout: {
      sections: [
        {
          id: uuid(),
          col: 12,
          name: "Section",
          fields: [
            {
              css: "",
              name: "location",
              type: ElementType.SELECT,
              label: "Location",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Medial",
                  value: "medial",
                },
                {
                  name: "Lateral",
                  value: "lateral",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please select Locations",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "location_comments",
              type: ElementType.TEXT,
              label: "Location Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter location comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "quality",
              type: ElementType.SELECT,
              label: "Quality",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Not Known",
                  value: "not_known",
                },
                {
                  name: "Aching",
                  value: " aching",
                },
                {
                  name: "Acute",
                  value: "acute",
                },
                {
                  name: "Burning",
                  value: "burning",
                },
                {
                  name: "Chronic",
                  value: "chronic",
                },
                {
                  name: "Constant",
                  value: "constant",
                },
                {
                  name: "Cramping",
                  value: "cramping",
                },
                {
                  name: "Crushing",
                  value: "crushing",
                },
                {
                  name: "Dull",
                  value: "dull",
                },
                {
                  name: "Electrical",
                  value: "electrical",
                },
                {
                  name: "Radiating Pain",
                  value: "radiating_pain",
                },
                {
                  name: "Sharp",
                  value: "sharp",
                },
                {
                  name: "Stabbing",
                  value: "stabbing",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please select qualities",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "quality_comments",
              type: ElementType.TEXT,
              label: "Quality Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Quality Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "severity",
              type: ElementType.SELECT,
              label: "Severity",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "1 out of 10",
                  value: "1_out_of_10",
                },
                {
                  name: "2 out of 10",
                  value: "2_out_of_10",
                },
                {
                  name: "3 out of 10",
                  value: "3_out_of_10",
                },
                {
                  name: "4 out of 10",
                  value: "4_out_of_10",
                },
                {
                  name: "5 out of 10",
                  value: "5_out_of_10",
                },
                {
                  name: "6 out of 10",
                  value: "6_out_of_10",
                },
                {
                  name: "7 out of 10",
                  value: "7_out_of_10",
                },
                {
                  name: "8 out of 10",
                  value: "8_out_of_10",
                },
                {
                  name: "9 out of 10",
                  value: "9_out_of_10",
                },
                {
                  name: "10 out of 10",
                  value: "10_out_of_10",
                },
                {
                  name: "Acute Distress",
                  value: "acute_distress",
                },
                {
                  name: "Critical",
                  value: "critical",
                },
                {
                  name: "LOC",
                  value: "loc",
                },
                {
                  name: "Mild",
                  value: "mild",
                },
                {
                  name: "Mild to Moderate",
                  value: "mild_to_moderate",
                },
                {
                  name: "Moderate",
                  value: "moderate",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please select Severity",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "severity_comments",
              type: ElementType.TEXT,
              label: "Severity Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Severity Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "duration",
              type: ElementType.SELECT,
              label: "Duration",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Getting Better",
                  value: "getting_better",
                },
                {
                  name: "Steady",
                  value: "steady",
                },
                {
                  name: " Have been increasing since onset",
                  value: "have_been_increasing_since_onset",
                },
                {
                  name: " % of time symptoms are experienced as in SOAP",
                  value: " % of time symptoms are experienced as in SOAP",
                },
                {
                  name: " has had same/similar condition in the past",
                  value: " has had same/similar condition in the past",
                },
                {
                  name: " Most symptomatic in morning",
                  value: " most symptomatic in morning",
                },
                {
                  name: "Most symptomatic in mid day",
                  value: "most symptomatic in mid day",
                },
                {
                  name: "Most symptomatic in evening",
                  value: "most symptomatic in evening",
                },
                {
                  name: "Wakes up from sleep",
                  value: "wakes up from sleep",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please select duration",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "duration_comments",
              type: ElementType.TEXT,
              label: "Duration Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Duration Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "onset_or_timing",
              type: ElementType.SELECT,
              label: "Onset / Timing",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Abrupt",
                  value: "abrupt",
                },
                {
                  name: "After Meal",
                  value: "after_meal",
                },
                {
                  name: "At Rest",
                  value: "at_rest",
                },
                {
                  name: "Awakened from Sleep",
                  value: "awakened_from_sleep",
                },
                {
                  name: "Continuous",
                  value: "continuous",
                },
                {
                  name: "Date of Occurrence",
                  value: "date_of_occurrence",
                },
                {
                  name: "Episodes",
                  value: "episodes",
                },
                {
                  name: "Gradual",
                  value: "gradual",
                },
                {
                  name: "Intermittent",
                  value: "intermittent",
                },
                {
                  name: "Primarily Nocturnal",
                  value: "primarily_nocturnal",
                },
                {
                  name: "Time not known",
                  value: "time_not_known",
                },
                {
                  name: "1 Day Ago",
                  value: "1_day_ago",
                },
                {
                  name: "Days Ago",
                  value: "days_ago",
                },
                {
                  name: "1 Week Ago",
                  value: "1_week_ago",
                },
                {
                  name: "Weeks ago",
                  value: "weeks_ago",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please Select Onset / Timing",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "onset_comments",
              type: ElementType.TEXT,
              label: "Onset Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Onset Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "context",
              type: ElementType.SELECT,
              label: "Context",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "At rest",
                  value: "at_rest",
                },
                {
                  name: "During physical exertion",
                  value: "during_physical_exertion",
                },
                {
                  name: "During mental exertion",
                  value: "during_mental_exertion",
                },
                {
                  name: "During a sporting activity",
                  value: "during_a_sporting_activity",
                },
                {
                  name: "At work",
                  value: "at_work",
                },
                {
                  name: "With familial stress",
                  value: "with_familial_stress",
                },
                {
                  name: "Mechanism issues",
                  value: "mechanism_issues",
                },
                {
                  name: "Post hospital visit",
                  value: "post_hospital_visit",
                },
                {
                  name: "Pre hospital visit",
                  value: "pre_hospital_visit",
                },
                {
                  name: "Gegan after discharge from hospital",
                  value: "began_after_discharge_from_hospital",
                },
                {
                  name: "He/She was recently treated by doctor",
                  value: "he/she_was_recently_treated_by_doctor",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please  select Contexts",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "context_comments",
              type: ElementType.TEXT,
              label: "Context Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Context Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "modifying_factors",
              type: ElementType.SELECT,
              label: "Modifying Factors",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Abated on their own",
                  value: "abated_on_their_own",
                },
                {
                  name: "Abated when on medication(s)",
                  value: "abated_when_on_medication(s)",
                },
                {
                  name: "Increased with inspiration",
                  value: "increased_with_inspiration",
                },
                {
                  name: "Exacerbate with movement",
                  value: "exacerbate_with_movement",
                },
                {
                  name: "Decrease with movement",
                  value: " decrease_with_movement",
                },
                {
                  name: "Have partially resolved seemingly on their own",
                  value: "have_partially_resolved_seemingly_on_their_own",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please select Modifying Factors",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "modifying_factors_comments",
              type: ElementType.TEXT,
              label: "Modifying Factors Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Modifying Factors Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "associated_symptoms",
              type: ElementType.SELECT,
              label: "Associated Symptoms",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Numbness",
                  value: "numbness",
                },
                {
                  name: "Tingling",
                  value: "tingling",
                },
                {
                  name: "Weakness",
                  value: "weakness",
                },
                {
                  name: "Headache",
                  value: "headache",
                },
                {
                  name: "Change in vision",
                  value: "change_in_vision",
                },
                {
                  name: "Dizziness",
                  value: "dizziness",
                },
                {
                  name: "Loss of bowel control",
                  value: "loss_of_bowel_control",
                },
                {
                  name: "Loss of bladder control",
                  value: "loss_of_bladder_control",
                },
                {
                  name: "Sexual dysfunction",
                  value: "sexual_dysfunction",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please Select Associated Symptoms",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "associated_symptoms_comments",
              type: ElementType.TEXT,
              label: "Associated Symptoms Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Associated Symptoms Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "944d6a43-372d-46d4-9b73-430928930df0",
              type: ElementType.TEXT,
              label: "Previous Treatment",
              column: 12,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              tableName: null,
              columnName: null,
              placeholder: "Please enter Previous Treatment",
              defaultValue: "",
              isMultiSelect: false,
            },
          ],
        },
      ],
    },
    name: "H&P CC / History of Present Illness",
    type: FormType.TEMPLATE,
    isSystemForm: true,
    isActive: true,
  },
  {
    layout: {
      sections: [
        {
          id: uuid(),
          col: 12,
          name: "SOAP Plan",
          isActive: true,
          fields: [
            {
              css: "",
              name: "labs",
              type: ElementType.SELECT,
              label: "Labs",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "LABS (to be done at Quest)",
                  value: "LABS (to be done at Quest)",
                },
                {
                  name: "LABS (to be done at LabCorp)",
                  value: "LABS (to be done at LabCorp)",
                },
                {
                  name: "LABS (to be done at Athena)",
                  value: "LABS (to be done at Athena)",
                },
                {
                  name: "Electrolyte panel",
                  value: "Electrolyte panel",
                },
                {
                  name: "Hepatic function panel",
                  value: "Hepatic function panel",
                },
                {
                  name: "Basic metabolic panel",
                  value: "Basic metabolic panel",
                },
                {
                  name: "Carbamazepine level",
                  value: "Carbamazepine level",
                },
                {
                  name: "Comp metabolic panel",
                  value: "Comp metabolic panel",
                },
                {
                  name: "Lipid panel",
                  value: "Lipid panel",
                },
                {
                  name: "Hepatitis panel",
                  value: "Hepatitis panel",
                },
                {
                  name: "Hypercoagulation Panel: Protein C; Protein S; Cardiolipin Ab; Russel viper venom; Antithrombin III; APCR; ANA; Sed rate",
                  value:
                    "Hypercoagulation Panel: Protein C; Protein S; Cardiolipin Ab; Russel viper venom; Antithrombin III; APCR; ANA; Sed rate",
                },
                {
                  name: "Homocysteine",
                  value: "Homocysteine",
                },
                {
                  name: "Autoimmune Panel: ANA; Anti SSA/SSB; Actin Ab IgG; Scleroderma Ab; Anti Jo-1 Ab; Anti DNA-DS; Anti RNP",
                  value:
                    "Autoimmune Panel: ANA; Anti SSA/SSB; Actin Ab IgG; Scleroderma Ab; Anti Jo-1 Ab; Anti DNA-DS; Anti RNP",
                },
                {
                  name: "Immunologic Indicated Panel: ANA; Rheum Arth factor; Complement C3; Immunofixation; IgA; IgM; IgG",
                  value:
                    "Immunologic Indicated Panel: ANA; Rheum Arth factor; Complement C3; Immunofixation; IgA; IgM; IgG",
                },
                {
                  name: "Infectious Disease Panel: HIV 1 Ab; HTLV I/II Ab; Lyme disease Ab; Hep B SAb; Hep C Ab",
                  value:
                    "Infectious Disease Panel: HIV 1 Ab; HTLV I/II Ab; Lyme disease Ab; Hep B SAb; Hep C Ab",
                },
                {
                  name: "Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
                  value:
                    "Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
                },
                {
                  name: "Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
                  value:
                    "Myasthenia Gravis Panel: AChR Binding Ab; AChR Blocking Ab; AChR Modulating Ab; Anti MUsk Ab",
                },
                {
                  name: "Infectious Neuropathies Panel: Cytomegalovirus; Herpes simplex virus IgG / IgM; Herpes zoster (shingles); Hep C Ab; Hep B 006510; HIV Ab; Lyme dis IgG/IgM Ab screen; Corynebacterium diphtheria culture; Mycobacterium leprae culture; Chagas dis",
                  value:
                    "Infectious Neuropathies Panel: Cytomegalovirus; Herpes simplex virus IgG / IgM; Herpes zoster (shingles); Hep C Ab; Hep B 006510; HIV Ab; Lyme dis IgG/IgM Ab screen; Corynebacterium diphtheria culture; Mycobacterium leprae culture; Chagas dis",
                },
                {
                  name: "Neuropathic Toxins Panel: Acrylamide; Arsenic; Lead; Mercury; Organophosphates; Platinum",
                  value:
                    "Neuropathic Toxins Panel: Acrylamide; Arsenic; Lead; Mercury; Organophosphates; Platinum",
                },
                {
                  name: "ANA",
                  value: "ANA",
                },
                {
                  name: "ANCA",
                  value: "ANCA",
                },
                {
                  name: "Anti DNA-DS",
                  value: "Anti DNA-DS",
                },
                {
                  name: "Anti Parietal Cell Ab",
                  value: "Anti Parietal Cell Ab",
                },
                {
                  name: "Anti Cardiolipin Ab",
                  value: "Anti Cardiolipin Ab",
                },
                {
                  name: "Anti Hu",
                  value: "Anti Hu",
                },
                {
                  name: "Anti Thrombin III",
                  value: "Anti Thrombin III",
                },
                {
                  name: "Anti Yo",
                  value: "Anti Yo",
                },
                {
                  name: "Campylobact. jejuni titer",
                  value: "Campylobact. jejuni titer",
                },
                {
                  name: "Complement C3 C4",
                  value: "Complement C3 C4",
                },
                {
                  name: "Complement CH50",
                  value: "Complement CH50",
                },
                {
                  name: "CBC with diff",
                  value: "CBC with diff",
                },
                {
                  name: "Ceruloplasmin",
                  value: "Ceruloplasmin",
                },
                {
                  name: "Serum copper",
                  value: "Serum copper",
                },
                {
                  name: "CPK",
                  value: "CPK",
                },
                {
                  name: "CRP",
                  value: "CRP",
                },
                {
                  name: "Cryoglobulin",
                  value: "Cryoglobulin",
                },
                {
                  name: "Factor V Leiden",
                  value: "Factor V Leiden",
                },
                {
                  name: "Folate",
                  value: "Folate",
                },
                {
                  name: "Glucose fasting",
                  value: "Glucose fasting",
                },
                {
                  name: "Glucose tolerance test 2hr",
                  value: "Glucose tolerance test 2hr",
                },
                {
                  name: "Glucose tolerance test 3hr",
                  value: "Glucose tolerance test 3hr",
                },
                {
                  name: "HgBA1C",
                  value: "HgBA1C",
                },
                {
                  name: "HIV-1/2 SCR w/RFX WB confirm",
                  value: "HIV-1/2 SCR w/RFX WB confirm",
                },
                {
                  name: "HIV-1 RNA PCR quantitative",
                  value: "HIV-1 RNA PCR quantitative",
                },
                {
                  name: "Homocysteine",
                  value: "Homocysteine",
                },
                {
                  name: "Immunofixation serum",
                  value: "Immunofixation serum",
                },
                {
                  name: "Intrinsic factor Ab",
                  value: "Intrinsic factor Ab",
                },
                {
                  name: "Iron (tot) IBC % sat",
                  value: "Iron (tot) IBC % sat",
                },
                {
                  name: "Iron total",
                  value: "Iron total",
                },
                {
                  name: "Lambert-Eaton syndrome Ab",
                  value: "Lambert-Eaton syndrome Ab",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select Labs",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "lab_comments",
              type: ElementType.TEXT,
              label: "Lab Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter lab comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "radiology",
              type: ElementType.SELECT,
              label: "Radiology",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Open MRI",
                  value: "Open MRI",
                },
                {
                  name: "Upright MRI",
                  value: "Upright MRI",
                },
                {
                  name: "MRI brain with and without contrast",
                  value: "MRI brain with and without contrast",
                },
                {
                  name: "MRI brain without contrast",
                  value: "MRI brain without contrast",
                },
                {
                  name: "MRI brain 3.0 T with and without contrast",
                  value: "MRI brain 3.0 T with and without contrast",
                },
                {
                  name: "MRI brain 3.0 T without contrast",
                  value: "MRI brain 3.0 T without contrast",
                },
                {
                  name: "MRA brain with and without contrast",
                  value: "MRA brain with and without contrast",
                },
                {
                  name: "MRA brain without contrast",
                  value: "MRA brain without contrast",
                },
                {
                  name: "CT scan brain with and without contrast",
                  value: "CT scan brain with and without contrast",
                },
                {
                  name: "CT scan brain without contrast",
                  value: "CT scan brain without contrast",
                },
                {
                  name: "CTA head and neck",
                  value: "CTA head and neck",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter radiology",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "radiology_comments",
              type: ElementType.TEXT,
              label: "Radiology Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Radiology Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "PT Recommendations",
              type: ElementType.SELECT,
              label: "PT Recommendations",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Evaluate and Teat",
                  value: "Evaluate and Teat",
                },
                {
                  name: "Exercise",
                  value: "Exercise",
                },
                {
                  name: "Manual Therapy",
                  value: "Manual Therapy",
                },
                {
                  name: "Chronic Pain Program",
                  value: "Chronic Pain Program",
                },
                {
                  name: "Posture/Position/Body Mechanics",
                  value: "Posture/Position/Body Mechanics",
                },
                {
                  name: "AROM",
                  value: "AROM",
                },
                {
                  name: "PROM",
                  value: "PROM",
                },
                {
                  name: "Back school",
                  value: "Back school",
                },
                {
                  name: "Gait training",
                  value: "Gait training",
                },
                {
                  name: "McKenzie Program",
                  value: "McKenzie Program",
                },
                {
                  name: "Aquatic Therapy",
                  value: "Aquatic Therapy",
                },
                {
                  name: "Neuro Re-education",
                  value: "Neuro Re-education",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter PT Recommendations",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "PT Recommendation Comments",
              type: ElementType.TEXT,
              label: "PT Recommendation Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter PT Recommendation Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "Home Health ",
              type: ElementType.SELECT,
              label: "Home Health ",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Skilled Nursing:",
                  value: "Skilled Nursing:",
                },
                {
                  name: "Eval & Instruct for:",
                  value: "Eval & Instruct for:",
                },
                {
                  name: "Medication",
                  value: "Medication",
                },
                {
                  name: "Pain",
                  value: "Pain",
                },
                {
                  name: "Cardiac",
                  value: "Cardiac",
                },
                {
                  name: "Diabetic Management",
                  value: "Diabetic Management",
                },
                {
                  name: "Respiratory",
                  value: "Respiratory",
                },
                {
                  name: "Physical Therapy:",
                  value: "Physical Therapy:",
                },
                {
                  name: "Weakness",
                  value: "Weakness",
                },
                {
                  name: "Ambulation/Gait",
                  value: "Ambulation/Gait",
                },
                {
                  name: "Balance",
                  value: "Balance",
                },
                {
                  name: "Transfers",
                  value: "Transfers",
                },
                {
                  name: "Bed Mobility",
                  value: "Bed Mobility",
                },
                {
                  name: "Fall Risk",
                  value: "Fall Risk",
                },
                {
                  name: "Range of Motion",
                  value: "Range of Motion",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Home Health ",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "Home health comments",
              type: ElementType.TEXT,
              label: "Home health comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Home health comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "Referrals ",
              type: ElementType.TEXT,
              label: "Referrals ",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Referrals ",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "Referral Comments",
              type: ElementType.TEXT,
              label: "Referral Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Referral Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "Education",
              type: ElementType.SELECT,
              label: "Education",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Alternative treatments",
                  value: "Alternative treatments",
                },
                {
                  name: "Drug interactions",
                  value: "Alternative Drug interactions",
                },
                {
                  name: "Handouts provided",
                  value: "Handouts provided",
                },
                {
                  name: "Medication side effects",
                  value: "Medication side effects",
                },
                {
                  name: "Pain management",
                  value: "Pain management",
                },
                {
                  name: "Potential adverse consequences if pregnant",
                  value: "Potential adverse consequences if pregnant",
                },
                {
                  name: "Recognizing stroke-like symptoms",
                  value: "Recognizing stroke-like symptoms",
                },
                {
                  name: "Risks of declining treatment",
                  value: "Risks of declining treatment",
                },
                {
                  name: "Risks/benefits of treatment plan",
                  value: "Risks/benefits of treatment plan",
                },
                {
                  name: "Signs of emergency",
                  value: "Signs of emergency",
                },
                {
                  name: "Symptom management",
                  value: "Symptom management",
                },
                {
                  name: "Written instructions for tapering/titrating medications",
                  value:
                    "Written instructions for tapering/titrating medications",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select Education",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "Education Comments",
              type: ElementType.TEXT,
              label: "Education Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Education Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "Diet",
              type: ElementType.SELECT,
              label: "Diet",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "1800 cal ADA diet",
                  value: "1800 cal ADA diet",
                },
                {
                  name: "1800 cal ADA diet",
                  value: "1800 cal ADA diet",
                },
                {
                  name: "2000 cal ADA diet",
                  value: "2000 cal ADA diet",
                },
                {
                  name: "1500 cal ADA diet",
                  value: "1500 cal ADA diet",
                },
                {
                  name: "Low fat diet",
                  value: "Low fat diet",
                },
                {
                  name: "Low sodium diet",
                  value: "Low sodium diet",
                },
                {
                  name: "Low cholesterol diet",
                  value: "Low cholesterol diet",
                },
                {
                  name: "Adequate nutritional intake",
                  value: "Adequate nutritional intake",
                },
                {
                  name: "Vitamin supplementation",
                  value: "Vitamin supplementation",
                },
                {
                  name: "Avoid alcohol",
                  value: "Avoid alcohol",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select a Diet",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "Diet Comments",
              type: ElementType.TEXT,
              label: "Diet Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please leave Diet Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "General Instructions ",
              type: ElementType.SELECT,
              label: "General Instructions ",
              column: 6,
              fieldId: uuid(),
              options: [
                {
                  name: "Activity as tolerated",
                  value: "Activity as tolerated",
                },
                {
                  name: "Activity as tolerated",
                  value: "Activity as tolerated",
                },
                {
                  name: "Avoid crowds",
                  value: "Avoid crowds",
                },
                {
                  name: "Avoid driving",
                  value: "Avoid driving",
                },
                {
                  name: "Avoid high risk activity due to seizures/LOC",
                  value: "Avoid high risk activity due to seizures/LOC",
                },
                {
                  name: "Follow exercise program",
                  value: "Follow exercise program",
                },
                {
                  name: "Follow facial exercise program",
                  value: "Follow facial exercise program",
                },
                {
                  name: "Increase activity level",
                  value: "Increase activity level",
                },
                {
                  name: "No heavy lifting",
                  value: "No heavy lifting",
                },
                {
                  name: "No heavy lifting more than 5 lbs",
                  value: "No heavy lifting more than 5 lbs",
                },
                {
                  name: "No heavy lifting more than 10 lbs",
                  value: "No heavy lifting more than 10 lbs",
                },
                {
                  name: "No heavy lifting more than 20 lbs",
                  value: "No heavy lifting more than 20 lbs",
                },
              ],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select General Instructions ",
              defaultValue: "",
              isMultiSelect: true,
            },
            {
              css: "",
              name: "General Instruction Comments",
              type: ElementType.TEXT,
              label: "General Instruction Comments",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please leave General Instruction Comments",
              defaultValue: "",
              isMultiSelect: false,
            },
          ],
        },
      ],
    },
    name: "SOAP Plan",
    type: FormType.TEMPLATE,
    isSystemForm: true,
    isActive: true,
  },
  {
    name: "Contact Info",
    isSystemForm: true,
    type: FormType.PRE_DEFINED,
    layout: {
      sections: [
        {
          id: uuid(),
          col: 12,
          name: "Address",
          fields: [
            {
              css: "",
              name: "zipCode",
              columnName: "zipCode",
              tableName: "Contacts",
              type: ElementType.TEXT,
              label: "Zip Code",
              column: 12,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter zip code",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "address1",
              columnName: "address",
              tableName: "Contacts",
              type: ElementType.TEXT,
              label: "Address 1",
              column: 12,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your address 1 ",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "address-2",
              columnName: "address2",
              tableName: "Contacts",
              type: ElementType.TEXT,
              label: "Address 2",
              column: 12,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your address 2",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "city",
              columnName: "city",
              tableName: "Contacts",
              type: ElementType.TEXT,
              label: "City",
              column: 4,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your city",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "state",
              columnName: "state",
              tableName: "Contacts",
              type: ElementType.SELECT,
              label: "State",
              column: 4,
              fieldId: uuid(),
              options: [
                {
                  name: "Alabama",
                  value: "Alabama - AL",
                },
                {
                  name: "Alaska",
                  value: "Alaska - AK",
                },
                {
                  name: "American Samoa",
                  value: "American Samoa - AS",
                },
                {
                  name: "Arizona",
                  value: "Arizona - AZ",
                },
                {
                  name: "Arkansas",
                  value: "Arkansas - AR",
                },
                {
                  name: "California",
                  value: "California - CA",
                },
                {
                  name: "Colorado",
                  value: "Colorado - CO",
                },
                {
                  name: "Connecticut",
                  value: "Connecticut - CT",
                },
                {
                  name: "Delaware",
                  value: "Delaware - DE",
                },
                {
                  name: "District Of Columbia",
                  value: "District Of Columbia - DC",
                },
                {
                  name: "Federated States Of Micronesia",
                  value: "Federated States Of Micronesia - FM",
                },
                {
                  name: "Florida",
                  value: "Florida - FL",
                },
              ],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please select your state",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "country",
              columnName: "country",
              tableName: "Contacts",
              type: ElementType.SELECT,
              label: "Country",
              column: 4,
              fieldId: uuid(),
              options: [
                {
                  name: "United States",
                  value: "United States",
                },
              ],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please Select a country",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "email",
              columnName: "email",
              tableName: "Contacts",
              type: ElementType.EMAIL,
              label: "Email",
              column: 12,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please enter your email address",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "phone",
              columnName: "phone",
              tableName: "Contacts",
              type: ElementType.NUMBER,
              label: "Home Phone",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please enter your Home Phone",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "mobile",
              columnName: "mobile",
              tableName: "Contacts",
              type: ElementType.NUMBER,
              label: "Mobile Phone",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please enter your Mobile Phone",
              defaultValue: "",
              isMultiSelect: false,
            },
          ],
        },
      ]
    },
  },
  {
    name: "Emergency Contact",
    type: FormType.PRE_DEFINED,
    isSystemForm: true,
    layout: {
      sections: [
        {
          id: uuid(),
          col: 12,
          name: "Emergency Contact",
          fields: [
            {
              css: "",
              name: "name",
              columnName: "name",
              tableName: "Contacts",
              type: ElementType.TEXT,
              label: "Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "relationship",
              columnName: "relationship",
              tableName: "Contacts",
              type: ElementType.SELECT,
              label: "Relationship",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_RELATIONSHIP_TYPE,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select a relationship",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "phone",
              columnName: "phone",
              tableName: "Contacts",
              type: ElementType.TEXT,
              label: "Home Phone",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your Home Phone",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "mobile",
              columnName: "mobile",
              tableName: "Contacts",
              type: ElementType.TEXT,
              label: "Mobile Phone",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Mobile Phone",
              defaultValue: "",
              isMultiSelect: false,
            },
          ],
        },
      ],
    },
  },
  {
    name: "Demographics",
    type: FormType.PRE_DEFINED,
    isSystemForm: true,
    layout: {
      sections: [
        {
          id: uuid(),
          col: 12,
          name: "Demographics",
          fields: [
            {
              css: "",
              name: "language",
              columnName: "language",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Language Spoken",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Language Spoken",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "race",
              columnName: "race",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Race",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_RACE,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select your race",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "ethnicity",
              columnName: "ethnicity",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Ethnicity",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_ETHNICITY,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select your Ethnicity",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "maritialStatus",
              columnName: "maritialStatus",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Marital Status",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_MARITAL_STATUS,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select a Marital Status",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "sexualOrientation",
              columnName: "sexualOrientation",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Sexual Orientation",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_SEXUAL_ORIENTATION,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Sexual Orientation",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "genderIdentity",
              columnName: "genderIdentity",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Gender Identity",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_GENDER_IDENTITY,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select your Gender Identity",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "sexAtBirth",
              columnName: "sexAtBirth",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Sex At Birth",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_GENDER_IDENTITY,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select your Sex At Birth",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "pronouns",
              columnName: "pronouns",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Pronouns",
              column: 6,
              fieldId: uuid(),
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select pronouns",
              defaultValue: "",
              options: MAPPED_PRONOUNS,
              isMultiSelect: false,
            },
            {
              css: "",
              name: "homeBound",
              columnName: "homeBound",
              tableName: "Patients",
              type: ElementType.RADIO,
              label: "Home Bound",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_HOMEBOUND,
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please select Home Bound",
              defaultValue: "",
              isMultiSelect: false,
            },

          ]
        }]
    }
  },
  {
    name: "Patient Info",
    type: FormType.PRE_DEFINED,
    isSystemForm: true,
    layout: {
      sections: [
        {
          id: uuid(),
          col: 12,
          name: "Patient Info",
          fields: [
            {
              css: "",
              name: "suffix",
              columnName: "suffix",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Suffix",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Suffix",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "firstName",
              columnName: "firstName",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "First Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please enter your First Name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "middleName",
              columnName: "middleName",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Middle Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your Middle Name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "lastName",
              columnName: "lastName",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Last Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please enter your Last Name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "firstNameUsed",
              columnName: "firstNameUsed",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "First Name Used",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your First Name Used",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "prefferedName",
              columnName: "prefferedName",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Preferred Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter Preferred Name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "previousFirstName",
              columnName: "previousFirstName",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Previous First Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your Previous First Name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "previouslastName",
              columnName: "previouslastName",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Previous Last Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your Previous Last Name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "motherMaidenName",
              columnName: "motherMaidenName",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "Mother's Maiden Name",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: false,
              textArea: false,
              placeholder: "Please enter your Mother's Maiden Name",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "ssn",
              columnName: "ssn",
              tableName: "Patients",
              type: ElementType.TEXT,
              label: "SSN",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please enter your SSN",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "dob",
              columnName: "dob",
              tableName: "Patients",
              type: ElementType.DATE,
              label: "Date of Birth",
              column: 6,
              fieldId: uuid(),
              options: [],
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please select your date of birth",
              defaultValue: "",
              isMultiSelect: false,
            },
            {
              css: "",
              name: "gender",
              columnName: "gender",
              tableName: "Patients",
              type: ElementType.SELECT,
              label: "Legal Sex",
              column: 6,
              fieldId: uuid(),
              options: MAPPED_GENDER_IDENTITY,
              errorMsg: "",
              required: true,
              textArea: false,
              placeholder: "Please select a Legal Sex",
              defaultValue: "",
              isMultiSelect: false,
            },
          ],
        },
      ],
    },
  }
]
