import { ElementType } from '../entities/element.entity'
import { FormType } from '../entities/form.entity'
//elements for seed
export const ElementTypeData = [
	{ type: ElementType.CHECKBOX },
	{ type: ElementType.DATE },
	{ type: ElementType.FILE },
	{ type: ElementType.EMAIL },
	{ type: ElementType.NUMBER },
	{ type: ElementType.RADIO },
	{ type: ElementType.SELECT },
	{ type: ElementType.TEXT },
]


//Form template
export const FormTemplates = [
	{
		layout: {
			sections: [
				{
					id: "8ada68b2-cd15-4370-af7c-2121e920ad63",
					col: 12,
					name: "Section",
					fields: [
						{
							css: "",
							name: "location",
							type: ElementType.SELECT,
							label: "Location",
							column: 6,
							fieldId: "db48cd38-115f-4c5a-ba99-0cb04d57dbde",
							options: [
								{
									name: "Medial",
									value: "medial",
								},
								{
									name: "Lateral",
									value: "lateral",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select Locations",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "location_comments",
							type: ElementType.TEXT,
							label: "Location Comments",
							column: 6,
							fieldId: "a35ef1eb-e538-48fb-b4e0-0cc78a9c219b",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter location comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "quality",
							type: ElementType.SELECT,
							label: "Quality",
							column: 6,
							fieldId: "25f4cfab-1338-4eab-958c-9f46b183d6e0",
							options: [
								{
									name: "Not Known",
									value: "not_known",
								},
								{
									name: "Aching",
									value: " aching",
								},
								{
									name: "Acute",
									value: "acute",
								},
								{
									name: "Burning",
									value: "burning",
								},
								{
									name: "Chronic",
									value: "chronic",
								},
								{
									name: "Constant",
									value: "constant",
								},
								{
									name: "Cramping",
									value: "cramping",
								},
								{
									name: "Crushing",
									value: "crushing",
								},
								{
									name: "Dull",
									value: "dull",
								},
								{
									name: "Electrical",
									value: "electrical",
								},
								{
									name: "Radiating Pain",
									value: "radiating_pain",
								},
								{
									name: "Sharp",
									value: "sharp",
								},
								{
									name: "Stabbing",
									value: "stabbing",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select qualities",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "quality_comments",
							type: ElementType.TEXT,
							label: "Quality Comments",
							column: 6,
							fieldId: "f62b2eec-72b1-44cc-bdea-2b01cdd1b931",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Quality Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "severity",
							type: ElementType.SELECT,
							label: "Severity",
							column: 6,
							fieldId: "a348f448-849b-4a20-9082-afbdc5ac6289",
							options: [
								{
									name: "1 out of 10",
									value: "1_out_of_10",
								},
								{
									name: "2 out of 10",
									value: "2_out_of_10",
								},
								{
									name: "3 out of 10",
									value: "3_out_of_10",
								},
								{
									name: "4 out of 10",
									value: "4_out_of_10",
								},
								{
									name: "5 out of 10",
									value: "5_out_of_10",
								},
								{
									name: "6 out of 10",
									value: "6_out_of_10",
								},
								{
									name: "7 out of 10",
									value: "7_out_of_10",
								},
								{
									name: "8 out of 10",
									value: "8_out_of_10",
								},
								{
									name: "9 out of 10",
									value: "9_out_of_10",
								},
								{
									name: "10 out of 10",
									value: "10_out_of_10",
								},
								{
									name: "Acute Distress",
									value: "acute_distress",
								},
								{
									name: "Critical",
									value: "critical",
								},
								{
									name: "LOC",
									value: "loc",
								},
								{
									name: "Mild",
									value: "mild",
								},
								{
									name: "Mild to Moderate",
									value: "mild_to_moderate",
								},
								{
									name: "Moderate",
									value: "moderate",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select Severity",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "severity_comments",
							type: ElementType.TEXT,
							label: "Severity Comments",
							column: 6,
							fieldId: "5da4c584-a5a4-4bc2-a2d9-f2de2b0ad9d6",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Severity Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "duration",
							type: ElementType.SELECT,
							label: "Duration",
							column: 6,
							fieldId: "519b1360-9b60-4ee7-a33d-edaa262a8e57",
							options: [
								{
									name: "Getting Better",
									value: "getting_better",
								},
								{
									name: "Steady",
									value: "steady",
								},
								{
									name: " Have been increasing since onset",
									value: "have_been_increasing_since_onset",
								},
								{
									name: " % of time symptoms are experienced as in SOAP",
									value: " % of time symptoms are experienced as in SOAP",
								},
								{
									name: " has had same/similar condition in the past",
									value: " has had same/similar condition in the past",
								},
								{
									name: " Most symptomatic in morning",
									value: " most symptomatic in morning",
								},
								{
									name: "Most symptomatic in mid day",
									value: "most symptomatic in mid day",
								},
								{
									name: "Most symptomatic in evening",
									value: "most symptomatic in evening",
								},
								{
									name: "Wakes up from sleep",
									value: "wakes up from sleep",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select duration",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "duration_comments",
							type: ElementType.TEXT,
							label: "Duration Comments",
							column: 6,
							fieldId: "eea8fa7d-ac3a-4dbf-9f65-c8f5d651ef96",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Duration Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "onset_or_timing",
							type: ElementType.SELECT,
							label: "Onset / Timing",
							column: 6,
							fieldId: "12471e12-d669-40ec-ac82-e1c705a5a477",
							options: [
								{
									name: "Abrupt",
									value: "abrupt",
								},
								{
									name: "After Meal",
									value: "after_meal",
								},
								{
									name: "At Rest",
									value: "at_rest",
								},
								{
									name: "Awakened from Sleep",
									value: "awakened_from_sleep",
								},
								{
									name: "Continuous",
									value: "continuous",
								},
								{
									name: "Date of Occurrence",
									value: "date_of_occurrence",
								},
								{
									name: "Episodes",
									value: "episodes",
								},
								{
									name: "Gradual",
									value: "gradual",
								},
								{
									name: "Intermittent",
									value: "intermittent",
								},
								{
									name: "Primarily Nocturnal",
									value: "primarily_nocturnal",
								},
								{
									name: "Time not known",
									value: "time_not_known",
								},
								{
									name: "1 Day Ago",
									value: "1_day_ago",
								},
								{
									name: "Days Ago",
									value: "days_ago",
								},
								{
									name: "1 Week Ago",
									value: "1_week_ago",
								},
								{
									name: "Weeks ago",
									value: "weeks_ago",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please Select Onset / Timing",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "onset_comments",
							type: ElementType.TEXT,
							label: "Onset Comments",
							column: 6,
							fieldId: "a4d1fc71-36a1-4968-947a-ac8a9af75279",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Onset Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "context",
							type: ElementType.SELECT,
							label: "Context",
							column: 6,
							fieldId: "0739cdcc-0ac2-4a4e-bc33-5d45e72757e8",
							options: [
								{
									name: "At rest",
									value: "at_rest",
								},
								{
									name: "During physical exertion",
									value: "during_physical_exertion",
								},
								{
									name: "During mental exertion",
									value: "during_mental_exertion",
								},
								{
									name: "During a sporting activity",
									value: "during_a_sporting_activity",
								},
								{
									name: "At work",
									value: "at_work",
								},
								{
									name: "With familial stress",
									value: "with_familial_stress",
								},
								{
									name: "Mechanism issues",
									value: "mechanism_issues",
								},
								{
									name: "Post hospital visit",
									value: "post_hospital_visit",
								},
								{
									name: "Pre hospital visit",
									value: "pre_hospital_visit",
								},
								{
									name: "Gegan after discharge from hospital",
									value: "began_after_discharge_from_hospital",
								},
								{
									name: "He/She was recently treated by doctor",
									value: "he/she_was_recently_treated_by_doctor",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please  select Contexts",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "context_comments",
							type: ElementType.TEXT,
							label: "Context Comments",
							column: 6,
							fieldId: "411f4623-707e-4f1f-9fa9-ab6af2d977fa",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Context Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "modifying_factors",
							type: ElementType.SELECT,
							label: "Modifying Factors",
							column: 6,
							fieldId: "5eef142c-59ab-41b3-a83a-aac9e3559383",
							options: [
								{
									name: "Abated on their own",
									value: "abated_on_their_own",
								},
								{
									name: "Abated when on medication(s)",
									value: "abated_when_on_medication(s)",
								},
								{
									name: "Increased with inspiration",
									value: "increased_with_inspiration",
								},
								{
									name: "Exacerbate with movement",
									value: "exacerbate_with_movement",
								},
								{
									name: "Decrease with movement",
									value: " decrease_with_movement",
								},
								{
									name: "Have partially resolved seemingly on their own",
									value: "have_partially_resolved_seemingly_on_their_own",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please select Modifying Factors",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "modifying_factors_comments",
							type: ElementType.TEXT,
							label: "Modifying Factors Comments",
							column: 6,
							fieldId: "360f47a0-4325-46f6-914c-7c6cbf7c1343",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Modifying Factors Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "associated_symptoms",
							type: ElementType.SELECT,
							label: "Associated Symptoms",
							column: 6,
							fieldId: "85f81e33-7b80-4039-906a-0da432015277",
							options: [
								{
									name: "Numbness",
									value: "numbness",
								},
								{
									name: "Tingling",
									value: "tingling",
								},
								{
									name: "Weakness",
									value: "weakness",
								},
								{
									name: "Headache",
									value: "headache",
								},
								{
									name: "Change in vision",
									value: "change_in_vision",
								},
								{
									name: "Dizziness",
									value: "dizziness",
								},
								{
									name: "Loss of bowel control",
									value: "loss_of_bowel_control",
								},
								{
									name: "Loss of bladder control",
									value: "loss_of_bladder_control",
								},
								{
									name: "Sexual dysfunction",
									value: "sexual_dysfunction",
								},
							],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please Select Associated Symptoms",
							defaultValue: "",
							isMultiSelect: true,
						},
						{
							css: "",
							name: "associated_symptoms_comments",
							type: ElementType.TEXT,
							label: "Associated Symptoms Comments",
							column: 6,
							fieldId: "c8254f45-963c-48fb-9b53-820b232aa23e",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Associated Symptoms Comments",
							defaultValue: "",
							isMultiSelect: false,
						},
						{
							css: "",
							name: "944d6a43-372d-46d4-9b73-430928930df0",
							type: ElementType.TEXT,
							label: "Previous Treatment",
							column: 12,
							fieldId: "e2b7d217-9816-4e52-9279-89a3db61ea81",
							options: [],
							errorMsg: "",
							required: false,
							textArea: false,
							tableName: null,
							columnName: null,
							placeholder: "Please enter Previous Treatment",
							defaultValue: "",
							isMultiSelect: false,
						},
					],
				},
			],
		},
		name: "H&P CC / History of Present Illness",
		type: FormType.TEMPLATE,
		isSystemForm: true,
		isActive: true
	}
]